feat(chip): Property `disabled` added
ionic-team/ionic-framework pull request #20658
Opened 2020-03-01 14:25 UTC by HansKrywaa

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [X] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: #19510

## What is the new behavior?

- Chips can be disabled

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

2020-03-20 19:06 UTC, liamdebeasi commented on core/src/components/chip/chip.scss
> +  opacity: .5;
```suggestion
  opacity: 0.4;
```

The MD spec has the opacity set to be 0.4 https://material.io/components/chips/

2020-03-20 19:22 UTC, HansKrywaa commented
Yeah of course: Requested Changes are added. I didn't found the Opacity in the MD Spec (and i still don't 😂), but adjusted to **0.4**.

2020-04-02 19:29 UTC, liamdebeasi commented
Thanks! Can you fix the failing build and merge conflicts?

2020-04-02 20:06 UTC, HansKrywaa commented
Done 😇

2020-04-11 16:13 UTC, shyamal890 commented
Also add CSS Shadow Parts to this component.

2020-04-13 13:25 UTC, liamdebeasi commented
@shyamal890 `ion-chip` does not have any internal elements that CSS Shadow Parts could help expose other than the ripple effect. Is there something you are trying to do with `ion-chip` that Shadow Parts would help solve?

2020-08-05 13:14 UTC, HansKrywaa commented
@shyamal890 This PR is just for the disabled Property. @liamdebeasi Anything i need to do here?

2020-10-22 18:50 UTC, liamdebeasi approved these changes
Looks good to me. @brandyscarney any feedback?

2020-11-03 17:59 UTC, liamdebeasi requested changes
We should prefer the actual boolean values for TypeScript users in the examples

2020-11-03 17:59 UTC, liamdebeasi commented on core/src/components/chip/usage/angular.md
> +<ion-chip disabled="true">
```suggestion
<ion-chip [disabled]="true">
```

2020-11-03 17:59 UTC, liamdebeasi commented on core/src/components/chip/usage/react.md
> +        <IonChip disabled="true">
```suggestion
        <IonChip disabled={true}>
```

2020-11-03 17:59 UTC, liamdebeasi commented on core/src/components/chip/usage/vue.md
> +  <ion-chip disabled="true">
```suggestion
  <ion-chip :disabled="true">
```

2020-11-03 19:29 UTC, brandyscarney approved these changes

2020-11-05 19:18 UTC, merged

2020-11-05 19:18 UTC, liamdebeasi commented
Merged. Thank you!