#19522 Generate web-types for @ionic/vue during build
ionic-team/ionic-framework pull request #22428
Opened 2020-11-04 13:26 UTC by piotrtomiak

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: #19522 

## What is the new behavior?

This PR introduces bundling of web-types with `@ionic/vue` for in-editor documentation support. The web-types standard is an open source standard supported so far only by WebStorm and is bundled with various other Vue libraries, like `vuetify`, `bootstrap-vue` or `quasar`. 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-11-04 17:43 UTC, liamdebeasi commented
Thank you! This looks great. I created a dev build and tested it in the latest version of WebStorm, and it is working well:

```
npm install @ionic/vue@5.5.0-dev.202011041734.2bd24d6 @ionic/vue-router@5.5.0-dev.202011041734.2bd24d6 --save-exact
```

2020-11-04 17:48 UTC, liamdebeasi requested changes
One small change, otherwise looks great.

2020-11-04 17:48 UTC, liamdebeasi commented on packages/vue/scripts/build-web-types.js
> +const docs = require("../../../docs/core.json")
```suggestion
const docs = require('@ionic/core/dist/docs.json')
```

Let's use the docs.json file output by ionic core as that is what we use in the other copy scripts (same exact file, just loading from a different location).

2020-11-05 14:34 UTC, liamdebeasi approved these changes
Thank you for this! I will make sure this gets into our next minor release.

2020-11-05 18:54 UTC, merged

2020-11-05 18:54 UTC, liamdebeasi commented
Merged. Thank you! This will be in our next minor release.

2020-11-06 12:36 UTC, piotrtomiak commented
Thank you!

2020-11-18 19:33 UTC, aparajita commented
Thank you @piotrtomiak!

2022-07-26 14:05 UTC, ddesmarais749 commented
I know this commit is old but seems like it is still an issues with Ionic v6.1.5. I can't get Webstorm autocomplete work.

Web-types.json is empty

The web-type.json in the "@ionic" node_modules looks like this :

![image](https://user-images.githubusercontent.com/86976221/181025003-2d31a524-7148-41b2-84a5-1d0efb7c9fc5.png)

Can anyone help me?