Update CODE_OF_CONDUCT.md
ionic-team/ionic-framework pull request #22619
Opened 2020-12-03 13:26 UTC by aleemosman

Change to Active Voice.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-12-15 21:28 UTC, brandyscarney requested changes

2020-12-15 21:28 UTC, brandyscarney commented on CODE_OF_CONDUCT.md
>  community include:
```suggestion
community include the ability to:
```

2020-12-15 21:28 UTC, brandyscarney commented on CODE_OF_CONDUCT.md
>  * Giving and gracefully accepting constructive feedback
```suggestion
* Give and gracefully accept constructive feedback
```

2020-12-15 21:28 UTC, brandyscarney commented on CODE_OF_CONDUCT.md
>    and learning from the experience
```suggestion
  and learn from the experience
```

2020-12-15 21:28 UTC, brandyscarney commented on CODE_OF_CONDUCT.md
>  * Focusing on what is best not just for us as individuals, but for the
```suggestion
* Focus on what is best not just for us as individuals, but for the
```

2021-02-11 14:35 UTC, merged

2021-02-11 14:35 UTC, liamdebeasi commented
Merged. Thank you!