feat(toast): add 'swipeGesture' property to dismiss toasts via swipe(…
ionic-team/ionic-framework pull request #23124
Opened 2021-03-31 16:12 UTC by evgeniy-skakun

…TakumaKira) - expanded

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ x ] Tests for the changes have been added (for bug fixes / features)
- [ x ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ x ] Build (`npm run build`) was run locally and any changes were pushed
- [ x ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ x ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

https://github.com/ionic-team/ionic-framework/issues/21769
-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ x ] No

## Other information

2021-03-31 16:15 UTC, liamdebeasi commented
Thanks for the PR. What is the difference between this PR and the previous toast swipe gesture PR? (https://github.com/ionic-team/ionic-framework/pull/22133).

2021-03-31 16:16 UTC, evgeniy-skakun commented
@liamdebeasi  Please check the extended version of the PR [ @TakumaKira ] https://github.com/ionic-team/ionic-framework/pull/22133

2021-03-31 16:17 UTC, evgeniy-skakun commented
@liamdebeasi  Added "vertical" and "horizontal" swipe

2021-03-31 16:20 UTC, liamdebeasi commented
What is the difference between a horizontal swipe and a swipe from the left or right?

2021-03-31 16:23 UTC, evgeniy-skakun commented
@liamdebeasi You can swipe in both directions instead of just one.

2021-03-31 16:30 UTC, liamdebeasi commented
Do you have any use cases for this? I wonder if it makes sense to just have the options be `'horizontal' | 'vertical'` and determine the direction based upon where the toast was presented from.

For example, if the toast was presented from the bottom and I had `swipeGesture="vertical"` set, I can't imagine there is a use case where I would want to swipe up to dismiss. I would expect that I would just swipe down to dismiss since it is closest to the bottom edge of the screen. 

Similarly, is there any benefit to only letting someone swipe to the left to dismiss versus being able to swipe to the left or the right?

2021-03-31 16:41 UTC, evgeniy-skakun commented
`vertical swipe` will be useful if the toast is placed in the center of the screen.

`horizontal swipe` can be useful if the application is used by left-handers and right-handers.

@liamdebeasi In any case, if you do not see any use in them, then they can be removed.

2021-03-31 16:48 UTC, liamdebeasi commented
Thanks for the clarification, that makes sense. I think in that case we can infer the direction based upon the `position` prop value.

If `position="bottom"` then swiping down would dismiss the toast.
If `position="top"` then swiping up would dismiss the toast.
If `position="middle` then swiping up or down would dismiss the toast.

Do you have any examples of the horizontal swipe in existing applications? I like the vertical swipe, but my concern with the horizontal swipe is that it is does not seem to exist in the Material Design spec.

2021-03-31 16:55 UTC, evgeniy-skakun commented
https://user-images.githubusercontent.com/58041146/113181917-f92b2b80-925a-11eb-9e01-b83b3fe38b45.mp4

Samsung allows you to swipe in both directions

2021-03-31 16:59 UTC, liamdebeasi commented
Those looks like Android-specific notification center components, not a toast/snackbar. Do you have any examples of this horizontal gesture with a toast/snackbar? 

For example, the Snackbar Flutter demo on https://material.io/components/snackbars only lets you do a vertical swipe.

2021-03-31 17:03 UTC, evgeniy-skakun commented
@liamdebeasi  I don't have an example app.

I can remove the `horizontal swipe` if you think it doesn't make sense.

2021-03-31 17:06 UTC, liamdebeasi commented
No problem, was just curious you knew of an example. I do see the benefit of this feature, so I think this is something we should add.

This is a new API, so it would need to go into a minor release. We are focusing on patch releases and the new major version of Ionic Framework at the moment, but I can add this to our project board and we will do a full review as we get closer to planning a new minor release.

2021-05-06 23:10 UTC, lodenrogue requested changes

2021-05-06 23:10 UTC, lodenrogue commented on core/src/components/toast/toast.tsx
> +    if (val > 1) {
Can this be simplified?

```
return val > 1 ? 1 : Math.max(0, val);
```

2021-09-13 15:43 UTC, reslear commented
any news?

2022-04-13 15:06 UTC, katche70 commented
Hi Ionic Team, 
It would be great if this feature comes in the official Ionic release

2022-05-12 13:23 UTC, thekhegay commented
Any updates?

2022-06-02 13:50 UTC, bstrasburg commented
Any updates ????

2022-06-28 16:24 UTC, philmmoore commented
I'd find this useful in my apps too :)

2022-07-06 10:14 UTC, EinfachHans commented
can't wait to se this in the framwork

2022-12-07 09:03 UTC, katche70 commented
Hey whats going on here with this open PR ? Nobody form ionic Team here to add this in official ionic release. Would by nice to have this feature, because it would be feel more native for ios user. Push Messages from ios simply can swipe up

2022-12-07 14:15 UTC, liamdebeasi commented
Hi everyone,

The team met a few weeks ago to discuss this PR, and we are interested in adding this feature. The next step is for the team to do a feature design document. This is where we determine the scope, requirements, and architecture of the feature to help ship a reliable API. Once that has been approved, someone from the team will review the PR and help make any changes necessary to get this PR ready to merge.

Our primary focus right now is getting Ionic 7.0 into beta, which is why you have not seen much movement on this PR over the past few weeks. While I do not have a timeline for when this will merge, we recognize that this is an important feature for Ionic developers. Let me know if there are any questions. Thanks!

2022-12-09 12:57 UTC, benmarsh commented
This is great news - thanks for the update @liamdebeasi :)

2023-07-03 04:32 UTC, rsammelson commented
Is there any update on this being completed? Would a new PR with conflicts resolved be useful to that process?

2023-07-24 06:50 UTC, sarevok89 commented
Is there any update on this? The PR has been opened more than 2 years above 😞

2023-07-28 07:04 UTC, Sigmale1000 commented
Any updates on the feature, since Ionic 7 is out?

2023-11-13 17:16 UTC, liamdebeasi commented
Hey there! Thanks for contributing this PR, and apologies for the delay in replying here. This feature was added to Ionic in https://github.com/ionic-team/ionic-framework/pull/28442. The work you did here helped us build out the final implementation, so we've given you co-author credit in the commit that was merged.

This feature will be available in an upcoming minor release of Ionic. I am going to close this, and thanks again for contributing to Ionic!

2023-11-13 17:16 UTC, closed without merging