feat(datetime): Add option to edit the label of the time selector
ionic-team/ionic-framework pull request #23577
Opened 2021-07-05 07:59 UTC by EinfachHans

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

The Label of the Time Selector of the datetime component was hardly set to "Time":

<img src="https://user-images.githubusercontent.com/20899975/124437033-eb63d580-dd76-11eb-99cc-72189db92cd1.png">

Issue Number: #23555 

## What is the new behavior?

Changes done to match logic with title or buttons:
- Property `showDefaultTimeLabel` added
- Text is editable via the `time-label` slot

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

2021-07-05 19:12 UTC, EinfachHans commented
don't know why the test failed 🤔

2021-07-06 15:31 UTC, liamdebeasi requested changes
Thanks for the PR! Can you remove the `core/package-lock.json` change? Also can you add some tests for this? My initial thought is to add a `tests/time-label` directory that shows a datetime with `showDefaultTimeLabel="true"`, a datetime with `showDefaultTimeLabel="false"`, and a datetime with a custom time label slot.

I would use the `minmax` test as a starting point.

2021-07-06 18:39 UTC, liamdebeasi requested changes
Can we add an `e2e.ts` file too that takes a screenshot so we can have a check for visual regressions? You can copy the file in `minmax`, just update the page url to point to `time-label`.

2021-07-06 18:39 UTC, liamdebeasi commented on core/src/components/datetime/test/time-label/index.html
> +        <h2>custom slot text</h2>
```suggestion
        <h2>Custom Time Label</h2>
```

2021-07-06 18:39 UTC, liamdebeasi commented on core/src/components/datetime/test/time-label/index.html
> +    <script type="module" src="../../../../../dist/ionic/ionic.esm.js"></script>
Please use 2 space indentation here

2021-07-06 18:49 UTC, EinfachHans commented
@liamdebeasi Done. Should be exactly like the **minmax** test now from space indentation 🤔

2021-07-07 13:01 UTC, liamdebeasi requested changes
One small punctuation fix (you will need to do `npm run build` again), and we need to fix the indentation in the HTML test but otherwise this is looking good

2021-07-07 13:01 UTC, liamdebeasi commented on core/src/components/datetime/datetime.tsx
> + * @slot time-label - The label for the time selector in the datetime
```suggestion
 * @slot time-label - The label for the time selector in the datetime.
```

2021-07-07 13:04 UTC, EinfachHans commented
The indentation should be now the same as in the minmax test, isn't that the correct one?

2021-07-07 13:07 UTC, liamdebeasi commented
The indentation is not the same.

Here is the indentation in the `minmax` file: 

![image](https://user-images.githubusercontent.com/2721089/124764125-a371b980-df02-11eb-87bb-7988968e53d5.png)

Here is the indentation in the `time-label` file:

![image](https://user-images.githubusercontent.com/2721089/124764167-ac628b00-df02-11eb-97c1-9a325cd1469a.png)

Do you have prettier enabled in your IDE? If so, I recommend turning that off as it may be automatically indenting files on save.

2021-07-07 13:18 UTC, EinfachHans commented
Damn yes i had such a feature enabled, sorry. Thanks for finishing! 😊

2021-07-07 13:18 UTC, liamdebeasi approved these changes
I found a few other changes I wanted to make so I fixed the indentation issue in my commit as well. I think this is good to go - great job!

2021-07-07 13:21 UTC, merged

2021-07-07 13:21 UTC, liamdebeasi commented
Merged. Thank you!!

2022-05-05 14:20 UTC, pierresh commented
Hello,

I think it would worth adding an example in the documentation about how to change the time label. _cancelText_, _clearText_, and _doneText_ can be changed easily, but I could not find any example on internet about how to deal with time label.