[Fix] Use last item in the Intersection API callback
ionic-team/ionic-framework pull request #23704
Opened 2021-07-30 02:49 UTC by Jacob-McKay

Fix for this issue: https://github.com/ionic-team/ionic-framework/issues/23703

There is a rare race condition you may experience on devices with slower CPU where the Intersection Observer API supplies multiple items to the callback, instead of only a single element which the previous code assumed it would get.  This changes takes the last item (which will be the most current information).

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-08-02 19:42 UTC, liamdebeasi requested changes

2021-08-02 19:42 UTC, liamdebeasi commented on core/src/components/img/img.tsx
> +        if (data[data.length - 1].isIntersecting) {
```suggestion
        /**
         * On slower devices, it is possible for an intersection observer entry to contain multiple 
         * objects in the array. This happens when quickly scrolling an image into view and then out of
         * view. In this case, the last object represents the current state of the component.
         */
        if (data[data.length - 1].isIntersecting) {
```

2021-08-02 19:42 UTC, liamdebeasi approved these changes
Thank you! This is good to merge when the tests pass.

2021-08-02 19:56 UTC, liamdebeasi commented on core/src/components/img/img.tsx
> +        if (data[data.length - 1].isIntersecting) {
```suggestion
        /**
         * On slower devices, it is possible for an intersection observer entry to contain multiple
         * objects in the array. This happens when quickly scrolling an image into view and then out of
         * view. In this case, the last object represents the current state of the component.
         */
        if (data[data.length - 1].isIntersecting) {
```

2021-08-03 00:57 UTC, Jacob-McKay commented
Ope, thought I that was a 'complete' button

2021-08-09 04:17 UTC, willmartindev approved these changes

2021-08-09 20:18 UTC, merged

2021-08-09 20:18 UTC, liamdebeasi commented
Merged. Thank you!