fix(popover): fix keyboard arrow navigation
ionic-team/ionic-framework pull request #23709
Opened 2021-08-01 20:11 UTC by willmartindev

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: resolves #23512 

## What is the new behavior?

- Keyboard navigation now works with arrow keys.
- `Home` and `End` key presses will also navigate to the first and last focusable item, respectively. 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2021-08-02 16:50 UTC, liamdebeasi requested changes
Small code change, but otherwise this looks great. Nice job adding the Home and End keys too.

2021-08-02 16:50 UTC, liamdebeasi commented on core/src/components/popover/utils.ts
> +  (item.shadowRoot?.querySelector('button.item-native') as HTMLElement)?.focus()
```suggestion
  const root = getElementRoot(item);
  const button = root.querySelector('button');
  
  if (button) {
    button.focus();
  }
```

Can we use the `getElementRoot` function here instead? https://github.com/ionic-team/ionic-framework/blob/7315e0157b917d2e3586c64f8082026827812943/core/src/utils/helpers.ts#L97

2021-08-03 13:24 UTC, liamdebeasi approved these changes
Code looks good - nice job. Once the build is passing this is good to merge.

2021-08-03 17:42 UTC, willmartindev commented
@liamdebeasi thanks for your help with the test!

2021-08-03 17:43 UTC, merged