feat(alert, toast): role can now be customized
ionic-team/ionic-framework pull request #23891
Opened 2021-09-08 14:23 UTC by willmartindev

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: resolves #23825 

## What is the new behavior?

- The ARIA role can now be customized.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-09-08 17:36 UTC, liamdebeasi reviewed
For `AlertInput`, we allows developers to pass in an `attributes` object: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/alert/alert-interface.ts#L38

Should we do the same thing here to keep the API consistent?

2021-09-08 17:45 UTC, willmartindev commented
> For `AlertInput`, we allows developers to pass in an `attributes` object: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/alert/alert-interface.ts#L38
> 
> Should we do the same thing here to keep the API consistent?

Yeah, I think that might be better. I can do that for both alert and toast.

2021-09-13 19:16 UTC, liamdebeasi reviewed
The code looks good. We need to add tests to verify this behavior. Might want to add a spec test since we are testing what attributes get rendered on the host.

2021-09-13 19:16 UTC, liamdebeasi commented on core/src/components/alert/alert-interface.ts
> +  additionalAttributes?: AlertAttributes;
Thoughts on calling this `htmlAttributes` similar to how we call it `cssClass`?

2021-09-14 17:18 UTC, liamdebeasi commented on core/src/components/alert/alert-interface.ts
> +  additionalAttributes?: AlertAttributes;
Also I think JSX uses this same naming convention for attributes: https://github.com/ionic-team/ionic-framework/blob/7315e0157b917d2e3586c64f8082026827812943/core/src/components/radio/radio.tsx#L165

2021-09-14 19:48 UTC, liamdebeasi requested changes

2021-09-14 19:48 UTC, liamdebeasi commented on core/src/components/toast/readme.md
> +| `htmlAttributes` | --               | Additional attributes to pass to the toast.
Please make sure you also update the `ToastOptions` and `AlertOptions` interfaces in the readmes

2021-09-14 20:22 UTC, liamdebeasi approved these changes
Great job!

2021-09-15 02:44 UTC, merged