feat(platform): add ability to override platform detection methods
ionic-team/ionic-framework pull request #23915
Opened 2021-09-11 03:50 UTC by willmartindev

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-09-13 17:30 UTC, liamdebeasi requested changes
This is looking great, but we do need to add tests to verify this works. Additionally, we need to update the Config docs in the `ionic-docs` repo to show usage, the `PlatformDetectionConfig` interface, etc.

2021-09-13 17:30 UTC, liamdebeasi commented on core/src/utils/config.ts
> +  platformDetection?: PlatformDetectionConfig;
Can we call this "platform"? (And also `PlatformConfig`)

2021-09-14 17:40 UTC, willmartindev commented on packages/react-router/test-app/src/index.tsx
> +
No, I can remove it since I added the spec test in core. 👍

2021-09-14 19:29 UTC, liamdebeasi approved these changes
Great job on this!

2021-09-14 19:49 UTC, merged