fix: add transition animation to another tab if direction was explicitely
ionic-team/ionic-framework pull request #23948
Opened 2021-09-17 15:49 UTC by TheTonnio

…tly defined

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-09-17 16:50 UTC, liamdebeasi requested changes
Thanks for making this PR! Let me know if you have any questions about adding the test we talked about on the issue thread.

2021-09-17 16:50 UTC, liamdebeasi commented on angular/src/providers/nav-controller.ts
> +    let isDirectionDefined = this.direction === 'forward' || this.direction === 'back';
This check can probably be done in the `setActive` function in `stack-controller.ts` so we dont need to export more data from this function. We should be able to do `direction !== 'root'`.

2021-11-22 20:36 UTC, liamdebeasi commented
@tonn1o Are you still interested in working on this fix?

2021-11-27 22:44 UTC, tonn1o commented
@liamdebeasi , sorry, I totally forgot that I've worked on the issue. Yes, I would like to proceed.

2022-07-05 17:19 UTC, liamdebeasi commented
Thanks for the PR, and apologies for the delay. We really appreciate all the hard work you put into creating this PR. At the moment, we are unable to accept this PR. The issue that this PR fixes is not a practice we are looking to recommend. I posted more details on the linked issue: https://github.com/ionic-team/ionic-framework/issues/19419#issuecomment-1175309392

I am going to close this. Thank you!

2022-07-05 17:19 UTC, closed without merging