feat(react): add setupIonicReact function
ionic-team/ionic-framework pull request #24254
Opened 2021-11-22 15:45 UTC by liamdebeasi

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/24139

With the Custom Elements build, we now need to call `initialize()`: https://github.com/ionic-team/ionic-framework/blob/next/packages/react/src/components/index.ts#L202. The problem is that this call also sets up the Ionic config. Given that Ionic config is not designed to be reactive, subsequent calls to `setupConfig` had no effect.

## What is the new behavior?

- After discussing with the team, we feel the best path forward is a (small) breaking change. Developers will be required to add `setupIonicReact` to their `App.tsx`/`App.jsx` file. This function will call `initialize` and allow developers to pass in a config, so it can be used instead of `setupConfig`.
- We explored non-breaking change options, but we think this change is the best option long term.
- I also noticed that setupConfig was being exported from Angular/React/Vue packages when it should not be. Developers should be going through the main entry points and not calling `setupConfig` on their own. If they need to eject from the normal process, they should call `initialize` instead.

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

## Other information

Migration:

1. Import `setupIonicReact` from '@ionic/react';
2. In `App.tsx`, call `setupIonicReact();`. Config should be passed here instead of `setupConfig`.
3. Remove any calls to `setupConfig`.

2021-11-22 18:03 UTC, amandaesmith3 commented
We'll also need to update the docs when this is merged: https://beta.ionicframework.com/docs/react/config

2021-11-22 18:11 UTC, amandaesmith3 requested changes
LGTM other than the BREAKING.md comment 👍 There's also updating the starter apps and docs, but those are other repos so we're good here otherwise.

2021-11-22 18:11 UTC, amandaesmith3 commented on BREAKING.md
> +### React
Should we also note that `setupConfig` is no longer exported for Angular and Vue?

2021-11-22 18:56 UTC, liamdebeasi commented
Starters have been updated in the `ionic6` branch: https://github.com/ionic-team/starters/compare/ionic6?expand=1
Docs have been updated in to the `react-config` branch: https://github.com/ionic-team/ionic-docs/compare/react-config?expand=1

2021-11-22 19:01 UTC, amandaesmith3 approved these changes

2021-11-22 20:29 UTC, merged

2023-01-04 05:19 UTC, developer82 commented
Hi,
I'm using the following:
```
"@ionic/react": "^6.0.1",
"@ionic/react-router": "^6.3.2",
```

And setting the following:
```
setupIonicReact({
    swipeBackEnabled: false
});
```

And it still doesn't work. Swipe back still working. The reason I wish to disable it is because it's so buggy. I have a tab navigation and if clicking the same tab it swipes back to it over and over and when swiping back sometimes the animation "jumps" and I get white screens.