feat(item): counter formatter to customize counter text display
ionic-team/ionic-framework pull request #24336
Opened 2021-12-07 03:32 UTC by sean-perkins

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

The counter text displays as `inputLength/maxLength` with no customization available to developers.

Issue Number: Closes #24327

## What is the new behavior?

Introduces a `counterFormatter` function on `ion-item` that allows developers to customize the display of the counter string.

The default behavior of `counterFormatter` is to display the text as `inputLength / maxLength`, such as `5 / 10` to align with the Material Design Specification.

Example use cases of this formatter could include displaying the remaining characters, such as "5 characters remaining" or giving additional context to what the max length represents, such as "5 / 10 characters". 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-03-08 15:03 UTC, amandaesmith3 approved these changes
🚀

2022-03-08 15:11 UTC, liamdebeasi requested changes

2022-03-08 15:11 UTC, liamdebeasi commented on core/src/components/item/item.tsx
> +    if (this.counter) {
This is redundant. The `updateCounterOutput` call already have an `this.counter` check

2022-03-08 15:11 UTC, liamdebeasi commented on core/src/components/item/readme.md
> +      <ion-item counter="true">
```suggestion
      <ion-item counter={true}>
```

2022-03-08 15:11 UTC, liamdebeasi commented on core/src/components/item/readme.md
> +      <ion-item counter="true" counterFormatter={(inputLength, maxLength) => `${maxLength - inputLength} characters remaining`}>
```suggestion
      <ion-item counter={true} counterFormatter={(inputLength, maxLength) => `${maxLength - inputLength} characters remaining`}>
```

2022-03-14 19:18 UTC, liamdebeasi approved these changes
One non-blocking question: Should `counterFormatter` default to `undefined`? That is what we do with the `isDateEnabled` property. I don't think if it matters here. The only benefit I can think of is a simpler stack trace and more consistency with other APIs.

Otherwise, good to go once the docs changes are updated.

2022-03-14 19:18 UTC, liamdebeasi commented on core/src/components/item/usage/vue.md
> +  <ion-item :counter="true" :counter-formatter="counterFormatter">
Should these two examples be reversed? The second one says "item counter formatter" but does not use the formatter.

2022-03-14 19:18 UTC, liamdebeasi commented on core/src/components/item/usage/vue.md
> +  <ion-item :counter="true" :counter-formatter="counterFormatter">
Looks like this also happens elsewhere

2022-03-14 20:38 UTC, merged