fix(input): autofill appearance for desktop platform
ionic-team/ionic-framework pull request #24443
Opened 2021-12-19 05:07 UTC by sean-perkins

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Input background appearance for autofill is applied to only the native input; which overlaps the label display. 

Issue Number: Resolves #18141

## What is the new behavior?

- Browsers that support `-webkit-autofill` will use a custom animation (with no effect)
- This animation is then detected through JS with `animationonstart` 
- Item style appearance is updated to apply background color for autofill at the main container

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Introduces two new internal CSS variables to the private API:
- `--background-autofill`
- `--color-autofill`

|Before|After|
|---|---|
|<img src="https://user-images.githubusercontent.com/13732623/146664577-924db137-9937-49b4-b1e4-2b98c1579aa4.png" width="350px" /> | <img src="https://user-images.githubusercontent.com/13732623/146664538-7143564e-c881-4416-84a0-d531dde98a56.png" width="350px" /> |

2021-12-19 05:08 UTC, sean-perkins commented on core/src/components/item/item.scss
> +  --background-autofill: rgb(232, 240, 254);
This value is taken from the light-theme Chrome settings. Need to discuss with the team on where global color tokens are located and how to handle theme support.

2021-12-20 15:01 UTC, amandaesmith3 requested changes

2021-12-20 15:01 UTC, amandaesmith3 commented on core/src/components/item/item.scss
> +  --color-autofill: black;
I believe this should be `var(--color)`. Not sure about the background though, would be good to discuss more internally.

2022-03-08 21:28 UTC, sean-perkins commented
We have decided to close out this PR for now and schedule work in the future to investigate a better `ion-item` API design, that alleviates this styling concern.

2022-03-08 21:28 UTC, closed without merging