fix(datetime): disable intersection observer during month update
ionic-team/ionic-framework pull request #24713
Opened 2022-02-03 22:40 UTC by sean-perkins

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

The next/previous buttons in the datetime is offset by 2 months. This is because the intersection observer is pre-maturely firing twice, during the re-render of the navigation to the desired month.

Issue Number: #24712

## What is the new behavior?

The intersection observer is disconnected before the state update/re-render and re-attached after the render and scroll offset has completed. This allows the swipe gesture behavior to operate correctly and fixes the issue for next/previous button to navigate to the desired month (1 month offset).

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-02-04 15:10 UTC, amandaesmith3 requested changes

2022-02-04 15:10 UTC, amandaesmith3 commented on core/src/components/datetime/datetime.tsx
> +          console.log('this being called');
Don't forget to remove this :eyes:

2022-02-04 15:25 UTC, sean-perkins commented on core/src/components/datetime/datetime.tsx
> +          console.log('this being called');
Good catch! 💯

2022-02-04 15:29 UTC, amandaesmith3 approved these changes

2022-02-04 16:39 UTC, merged

2023-10-23 21:58 UTC, Manishatah commented
Hi Guys,
I am on v 6.1.2 and the issue still persists.
 @amandaejohnston  @sean-perkins

2023-10-24 14:16 UTC, amandaejohnston commented
@Manishatah If the issue still occurs on the latest version of Ionic (currently 7.5.1), please open a new issue and include a code reproduction.