fix(datetime): improve datetime sizing in modals
ionic-team/ionic-framework pull request #24762
Opened 2022-02-09 23:11 UTC by sean-perkins

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

When an `ion-datetime` has a sub-pixel width (either explicitly or through an auto-sizing layout), the intersection observer is unable to detect the intersecting threshold of 100% (`1`).

This results in the month navigation breaking, months updating sporadically on click and overall broken functionality. 

Issue Number: #23992

## What is the new behavior?

By applying a root margin to the intersection observer of `1px`, it accounts for the difference of the sub-pixel sizing and appropriately fires the intersection observer when the month is intersecting.

This fixes all the broken behavior with the calendar month not appropriately updating. 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-02-11 19:03 UTC, amandaesmith3 approved these changes
Nice find :eyes: Incidentally, this also seems to fix https://github.com/ionic-team/ionic-framework/issues/23985; it even looks good on Firefox.

2022-02-16 01:08 UTC, liamdebeasi requested changes
Just had a thought... can we add a test to verify this fixed behavior too? https://github.com/ionic-team/ionic-framework/pull/24762#pullrequestreview-880570710

2022-02-16 14:39 UTC, sean-perkins commented
> Just had a thought... can we add a test to verify this fixed behavior too? [#24762 (review)](https://github.com/ionic-team/ionic-framework/pull/24762#pullrequestreview-880570710)

I was unable to replicate that issue in Chrome (the original reported issue) or in Firefox (the follow-up comment). I believe the original issue was a Chrome specific version that has since been fixed. 

I can add a smoke test though, just to make sure it works with a zoom in/out active.

2022-02-22 19:15 UTC, liamdebeasi approved these changes

2022-02-22 21:05 UTC, merged