fix(datetime): confirm will use selected date
ionic-team/ionic-framework pull request #24827
Opened 2022-02-21 18:38 UTC by sean-perkins

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

When confirming the date using datetime's `confirm()` method, it will use the working parts (visible calendar month) instead of the active parts (selected calendar month). This results in incorrect date values when a user selects a date, navigates next/previous to a different calendar month and uses the `confirm()` API to close/dismiss the datetime overlay.

Issue URL: #24823

## What is the new behavior?

- The `confirm()` API uses the active parts when setting the current value.
- Navigating to next/previous months will not affect the date value when using `confirm()`, unless the user selects a new date inside that month.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-02-22 14:26 UTC, liamdebeasi requested changes

2022-02-22 16:28 UTC, amandaesmith3 approved these changes
LGTM once Liam's comment is addressed 👍

2022-02-22 17:04 UTC, sean-perkins commented on core/src/components/datetime/test/confirm-date/index.html
> +      font-weight: normal;
Is there a way to override the locale & value of the datetime for a specific test? I tried this:
```
await page.$eval('#modal ion-datetime', (el: any) => {
  el.locale = 'en-US';
  el.value = '2021-11-22';
});

await page.waitForChanges();
```

But it does not appear to override the initial values for the test. 

I'm open to other ways of testing this as well. I just need to open the datetime with a value, navigate to a next/prev month, use the `.confirm()` API and check the datetime's value.

2022-02-23 19:39 UTC, sean-perkins commented on core/src/components/datetime/test/basic/e2e.ts
> +    await page.waitForTimeout(350);
I need to fix this before merging.

2022-02-23 20:14 UTC, merged