feat(modal): add canDismiss support for regular modals
ionic-team/ionic-framework pull request #24919
Opened 2022-03-10 20:17 UTC by liamdebeasi

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Part of https://github.com/ionic-team/ionic-framework/issues/22297

## What is the new behavior?

- This adds the base implementation for regular modals.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-03-10 20:32 UTC, sean-perkins requested changes

2022-03-10 20:32 UTC, sean-perkins commented on core/src/components/modal/test/canDismiss/e2e.ts
> +  let page;
```suggestion
  let page: E2EPage;
```

& add `E2EPage` to the import for `@stencil/core/testing`.

2022-03-10 21:39 UTC, sean-perkins commented on core/src/components/modal/test/canDismiss/e2e.ts
> +import { newE2EPage } from '@stencil/core/testing';
```suggestion
import { E2EPage, newE2EPage } from '@stencil/core/testing';
```

2022-03-11 16:53 UTC, sean-perkins approved these changes

2022-03-11 16:56 UTC, amandaesmith3 approved these changes

2022-03-11 17:43 UTC, merged