test(picker-column-internal): migrate tests to playwright
ionic-team/ionic-framework pull request #25211
Opened 2022-04-28 18:40 UTC by sean-perkins

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): Test migration

## What is the current behavior?

## What is the new behavior?

- Migrates Puppeteer tests to Playwright
- Skips test for `ionChange` event emission on Firefox, due to: https://bugzilla.mozilla.org/show_bug.cgi?id=1766890
- Introduces new expect assertion `toHaveReceivedEvent` (matches custom Stencil Puppeteer behavior)

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Opted for not fixing the Firefox bug. Attempts to correct the behavior, negatively impact the snap behavior on Chrome and Safari.

2022-04-28 20:39 UTC, sean-perkins commented
I need to explore a little bit more how to handle the custom type declarations that Playwright instructs for custom assertions. The existing solution seems to conflict with bundled output. Likely need to ignore it from compilation/output.

2022-04-29 13:54 UTC, liamdebeasi approved these changes

2022-04-29 14:15 UTC, amandaejohnston requested changes

2022-04-29 17:03 UTC, amandaejohnston approved these changes

2022-04-29 17:04 UTC, merged