test(textarea): migrate tests to playwright
ionic-team/ionic-framework pull request #25512
Opened 2022-06-21 17:57 UTC by sean-perkins

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): Test migration

## What is the current behavior?

Tests are written in Puppeteer. 

Issue URL: N/A

## What is the new behavior?

- Migrate tests to Playwright
- Capture floating label test separately, as initial test template was setting value in a timeout

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-06-21 20:13 UTC, liamdebeasi commented on core/src/components/textarea/test/a11y/textarea.e2e.ts
> +    );
Optional

```suggestion
    await page.setContent(`
      <ion-item>
        <ion-label>A11y Test</ion-label>
        <ion-textarea></ion-textarea>
      </ion-item>
    `);
```

2022-06-21 20:13 UTC, liamdebeasi commented on core/src/components/textarea/test/a11y/textarea.e2e.ts
> +    expect(ariaLabelledBy).toBe(null);
You did this because `expect(...).toHaveAttribute` doesn't accept `null` right?

2022-06-21 20:21 UTC, sean-perkins commented on core/src/components/textarea/test/autogrow/textarea.e2e.ts
> +
I'll add a test for this 👍

2022-06-22 14:03 UTC, amandaejohnston requested changes

2022-06-22 14:03 UTC, amandaejohnston commented on core/src/components/textarea/test/basic/textarea.e2e.ts
> +  test.describe('with floating labels', () => {
This looks to be a duplicate test of the `#dynamicValue` textarea in the above screenshot.

2022-06-22 14:03 UTC, amandaejohnston commented on core/src/components/textarea/test/standalone/textarea.e2e.ts
> +  test('should not have visual regressions', async ({ page }) => {
The ASCII art hasn't rendered correctly in these:
- `core/src/components/textarea/test/standalone/textarea.e2e.ts-snapshots/textarea-standalone-diff-ios-ltr-Mobile-Firefox-linux.png`
- `core/src/components/textarea/test/standalone/textarea.e2e.ts-snapshots/textarea-standalone-diff-ios-rtl-Mobile-Firefox-linux.png`
- `core/src/components/textarea/test/standalone/textarea.e2e.ts-snapshots/textarea-standalone-diff-md-ltr-Mobile-Firefox-linux.png`
- `core/src/components/textarea/test/standalone/textarea.e2e.ts-snapshots/textarea-standalone-diff-md-rtl-Mobile-Firefox-linux.png`

2022-06-22 14:44 UTC, liamdebeasi commented on core/src/components/textarea/test/autogrow/textarea.e2e.ts
> +    expect(await page.screenshot()).toMatchSnapshot(`textarea-autogrow-initial-${page.getSnapshotSettings()}.png`);
+1 to this

2022-06-22 14:45 UTC, liamdebeasi commented on core/src/components/textarea/test/autogrow/textarea.e2e.ts
> +        `\nMy life got flipped-turned upside down`,
Disappointed we didn't use the Bee Movie script, but I'll live 🐝

2022-07-05 20:06 UTC, sean-perkins commented
Auto grow continues to be extremely flaky with capturing consistent screenshots with the existing implementation pattern. I'm going to see if it is a timing issue. If not, I may need to skip those screenshot captures until #25512.

2022-07-06 16:11 UTC, amandaejohnston approved these changes
LGTM once the below comment is resolved 👍

2022-07-06 17:21 UTC, merged