fix(angular): warn devs that standalone components are not supported
ionic-team/ionic-framework pull request #25516
Opened 2022-06-21 21:14 UTC by sean-perkins

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): 

## What is the current behavior?

When developers make use of routable standalone components with Ionic, they will receive a generic error that gives no context to the issue or current support status of the feature.

Issue URL: Internal

## What is the new behavior?

- Warn developers when they attempt to use standalone components with `ion-router-outlet`

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Dev-build: `6.1.11-dev.11655864040.13968d31`

You can test with this demo repo and the dev-build: https://github.com/sean-perkins/angular-14-demo

<img width="588" alt="Screen Shot 2022-06-21 at 10 24 49 PM" src="https://user-images.githubusercontent.com/13732623/174929853-f1da0185-413b-4253-86fd-41e8d04acaa2.png">

2022-06-21 21:34 UTC, liamdebeasi requested changes

2022-06-21 21:34 UTC, liamdebeasi commented on angular/src/directives/navigation/ion-router-outlet.ts
> +        throw new Error(`[Ionic Error] Standalone components are not currently supported with ion-router-outlet.
Are we able to make this a warning? Angular will already throw an error and I worry that developers will see this and think they "broke" something in Ionic.

2022-06-21 21:34 UTC, liamdebeasi commented on angular/src/directives/navigation/ion-router-outlet.ts
> +      if (snapshot.component) {
Can we add a comment that explains why we check for `snapshot.component`? Is it that only standalone components always have this populated?

2022-06-21 21:34 UTC, liamdebeasi commented on angular/src/directives/navigation/ion-router-outlet.ts
> +      if (snapshot.component) {
Can we add a TODO for FW-1631 to remove this check if we add support for standalone components?

2022-06-22 14:09 UTC, amandaejohnston approved these changes

2022-06-22 14:43 UTC, liamdebeasi approved these changes

2022-06-23 16:45 UTC, merged