fix(datetime): date and time picker accessibility
ionic-team/ionic-framework pull request #25980
Opened 2022-09-20 16:58 UTC by sean-perkins

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Datetime has several accessibility issues:
- The icon in the month/year dropdown is announced to screen readers
- All working part calendar days are announced to screen readers (e.g. non-visible months are read)
- Users cannot navigate focus easily from the calendar body to the time picker
- Time picker does not announce value changes to screen readers
- Time picker does not announce total available options in each column
- Time picker does not announce the type of column being focused

Issue URL: Internal

## What is the new behavior?

- The icon in the month/year dropdown is not announced to screen readers
- Only the active month is announced to screen readers
- Users can easily navigate from the calendar body to the time picker
- Time picker announces value changes to screen readers
- Time picker announces the total number of items available in each column
- Time picker announces the type of column being focused (e.g. "5 o'clock" or "10 minutes")

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

**Date picker**

|Before|After|
|------|------|
|<video src="https://user-images.githubusercontent.com/13732623/191318874-4832e325-ae13-466f-8d1e-6b01483782c2.mp4"></video>|<video src="https://user-images.githubusercontent.com/13732623/191318174-433429b5-e15a-4c03-8348-d04df616096b.mp4"></video>|

2022-09-20 17:06 UTC, sean-perkins commented on core/src/components/datetime/datetime.tsx
> +            popoverRef.presentFromTrigger(
Using `presentFromTrigger` allows us to configure if the direct descendent should be focused when the popover is presented. We want to focus the direct descendent so the hours picker column is announced immediately (this happens on iOS).

2022-09-20 17:06 UTC, sean-perkins commented on core/src/components/picker-column-internal/picker-column-internal.tsx
> +      this.focusActiveItem();
Focusing the active picker column item on value change will cause the screen reader to accurately announce the value change.

2022-09-20 17:06 UTC, sean-perkins commented on core/src/components/picker-column-internal/picker-column-internal.tsx
> +    this.focusActiveItem();
Additionally we need to focus the active item manually when the picker column receives focus, so that the active item is correctly announced.

2022-09-20 17:06 UTC, sean-perkins commented on core/src/components/picker-column-internal/picker-column-internal.tsx
> +              role="radio"
Role `radio` seemed like the most appropriate role based on the ARIA spec (single selection allowed in a group at a time).

2022-09-20 17:06 UTC, sean-perkins commented on core/src/components/picker-column-internal/picker-column-internal.tsx
> +        <div class="picker-item picker-item-empty" aria-hidden="true">
The empty picker items are hidden from screen readers, otherwise they are read when the screen reader announces the entire section.

2022-09-20 17:06 UTC, sean-perkins commented on core/src/components/datetime/datetime.tsx
> +        aria-hidden={!isWorkingMonth ? 'true' : 'false'}
Hiding the months outside of the active working month, results in the screen reader not announcing the previous and next month days when the group is announced.

2022-09-20 17:06 UTC, sean-perkins commented on core/src/components/datetime/datetime.tsx
> +                  aria-hidden="true"
This icon was being announced as "image" when the section was being read. Hiding it from screen readers as that information is not valuable or useful.

2022-09-20 20:33 UTC, sean-perkins commented on core/src/components/picker-column-internal/picker-column-internal.tsx
> +    this.focusActiveItem();
Unable to make this improvement right now. The input mode implementation is not compatible with the button being focused when the column is focused. The input requires the keypress events to be bubbled from the picker column being focused.

2022-09-23 21:33 UTC, liamdebeasi requested changes
Can we break these changes out into separate PRs? FW-2184 only deals with the calendar body

2022-09-26 19:45 UTC, sean-perkins commented
Sure thing!

2022-09-27 15:37 UTC, sean-perkins commented
All behavior in this PR have been split into separate pull requests; closing.

2022-09-27 15:37 UTC, closed without merging