fix(datetime): wheel picker font resizing works on android
ionic-team/ionic-framework pull request #26017
Opened 2022-09-26 19:46 UTC by liamdebeasi

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue URL: 

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2022-09-27 13:15 UTC, liamdebeasi commented
The screenshots are failing due to font family diffs. This is fixed by https://github.com/ionic-team/ionic-framework/pull/26020.

2022-09-28 15:31 UTC, amandaejohnston requested changes

2022-09-28 15:31 UTC, amandaejohnston commented on core/src/components/picker-column-internal/picker-column-internal.tsx
> +      const top = Math.round(targetOffsetFromTop - midpoint);
https://user-images.githubusercontent.com/90629384/192820135-e2c14721-88fb-4aed-a157-eea30811f826.mp4 I'm seeing a weird issue where the time picker on the basic datetime opens with the wheels in the wrong positions, and then things jump around when I make the first click.

2022-09-28 18:24 UTC, liamdebeasi commented
Going to move this back to a draft until I can figure out a better way to handle scrolling.

2022-10-03 14:55 UTC, liamdebeasi commented
Closing for now until I can loop back to this.

2022-10-03 14:55 UTC, closed without merging