WIP feat(input): add labelPlacement
ionic-team/ionic-framework pull request #26206
Opened 2022-11-01 20:58 UTC by liamdebeasi

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue URL: 

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2022-11-04 15:09 UTC, amandaejohnston requested changes

2022-11-04 18:08 UTC, liamdebeasi commented on core/src/components/input/input.scss
> +  @include margin(0, 8px, 0, 0);
I fixed this in https://github.com/ionic-team/ionic-framework/pull/26226. Do you want me to merge the changes into this PR instead?

2022-11-04 18:19 UTC, amandaejohnston commented on core/src/components/input/input.scss
> +  @include margin(0, 8px, 0, 0);
Aha, nah that works 👍 As long as it's addressed somewhere 😆

2022-11-04 18:19 UTC, amandaejohnston approved these changes

2022-11-08 15:29 UTC, sean-perkins approved these changes

2022-11-08 15:58 UTC, merged