feat(checkbox): add basic styling and CSS vars for new syntax
ionic-team/ionic-framework pull request #26460
Opened 2022-12-09 18:55 UTC by amandaejohnston

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue URL: 

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2022-12-09 20:52 UTC, amandaejohnston commented
There are some errant datetime screenshots in here still, but I'm putting this up for review now to get the relevant stuff looked over. I'll circle back around to the tests as needed once I've got all the feature work done.

2022-12-12 19:23 UTC, liamdebeasi requested changes
Noticed that some legacy screenshots got deleted:

`core/src/components/checkbox/test/legacy/basic/checkbox.e2e.ts-snapshots/checkbox-basic-md-ltr-Mobile-Safari-linux.png`
`core/src/components/checkbox/test/legacy/basic/checkbox.e2e.ts-snapshots/checkbox-basic-md-rtl-Mobile-Safari-linux.png`

This is due to the change in filename change in the basic legacy test, right?

I also am seeing a handful of non-checkbox screenshot diffs (datetime, picker-internal, textarea). Can't quite figure out what's different, so maybe a subtle difference?

2022-12-12 19:23 UTC, liamdebeasi commented on core/src/components/checkbox/test/basic/checkbox.e2e.ts
> +    skip.rtl();
Can we disable per-mode checks?

2022-12-12 19:23 UTC, liamdebeasi commented on core/src/components/checkbox/test/indeterminate/checkbox.e2e.ts
> +  test('should not have visual regressions', async ({ page }) => {
Does indeterminate state have RTL-specific logic? If not, we can probably disable the rtl check

2022-12-13 15:11 UTC, liamdebeasi approved these changes
Good to go once previous comments are addressed

2022-12-13 19:01 UTC, amandaejohnston commented
> Noticed that some legacy screenshots got deleted:
> 
> `core/src/components/checkbox/test/legacy/basic/checkbox.e2e.ts-snapshots/checkbox-basic-md-ltr-Mobile-Safari-linux.png` `core/src/components/checkbox/test/legacy/basic/checkbox.e2e.ts-snapshots/checkbox-basic-md-rtl-Mobile-Safari-linux.png`
> 
> This is due to the change in filename change in the basic legacy test, right?

Yeah, those screenshots registered as removed and re-added rather than just renamed for some reason. The legacy screenshots that the diff is showing as net-new are the same as the ones that were "removed."

2022-12-13 21:28 UTC, sean-perkins approved these changes

2022-12-15 20:52 UTC, amandaejohnston commented
Removed the new CSS properties and some extra code related to them; re-requesting review just in case 👀 I left the background props renamed to avoid confusion, since `--background` still sounds like it should be the background for the whole container.

2022-12-15 21:56 UTC, liamdebeasi approved these changes

2022-12-19 15:50 UTC, amandaejohnston commented
Ah, looks like those failing tests are actually screenshot regressions 🤔 Gonna run the update job and make sure nothing goes awry there.

2022-12-19 16:48 UTC, amandaejohnston commented
Okay, should be good now 👍

2022-12-20 16:10 UTC, sean-perkins approved these changes
Clicked through the examples, things look good to me 👍

2022-12-20 17:11 UTC, merged