feat(checkbox): add labelPlacement and justify props
ionic-team/ionic-framework pull request #26467
Opened 2022-12-12 18:31 UTC by amandaejohnston

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the new behavior?

Adds the `labelPlacement` and `justify` props to checkbox, along with screenshot tests. Also adds an a11y test and a fix to get that passing.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-12-13 15:19 UTC, liamdebeasi reviewed
Noticing some misalignment in `core/src/components/checkbox/test/label/checkbox.e2e.ts-snapshots/checkbox-label-start-justify-start-md-rtl-Mobile-Chrome-linux.png`. Looks like there's some extra space above the checkbox?

2022-12-13 19:19 UTC, amandaejohnston commented
@liamdebeasi That looks to just be a browser rendering quirk; the text is 19px tall with the current font choice, and the checkbox is 18px, so it has to be off-center one way or the other. I confirmed that the bounding boxes line up perfectly at the bottom edge.

2022-12-14 20:05 UTC, liamdebeasi requested changes
A few things:

1. Can we add a test to make sure the label text gets truncated with ellipses properly? (in general, not just with `labePlacement="fixed"`
2. I'm seeing that an empty `<label>` element is still rendered inside of the parent `<label>` This likely left over from the legacy rendering.
3. Is `aria-label` functionality part of this PR? If so, we should add an a11y test with automated axe checks.

2022-12-14 20:05 UTC, liamdebeasi commented on core/src/components/checkbox/checkbox.scss
> +}
I recommend wrapping `.checkbox-icon` in a `.native-wrapper` element like the other new form controls have. This way you can apply margins to the icon container and not worry about interfering with the SVG itself.

From there, you can get rid of these `.checkbox-icon` selectors and apply the following CSS:

```
.native-wrapper {
  display: flex;

  align-items: center;
}
```

You can look at the Toggle CSS code to see how it was done there too.

2022-12-16 17:44 UTC, amandaejohnston commented
Adjusted a few things per the above 👀 (cc @sean-perkins This is ready for review for real now)

2022-12-16 19:08 UTC, sean-perkins commented
Implementation and changes look good to me! One question, is there a reason we aren't doing `item` tests as part of this PR?

Comparing against toggle: https://github.com/ionic-team/ionic-framework/pull/26314 and I know I also ran into adding those tests for label placement on checkbox. Is that test criteria covered in existing/other tests?

2022-12-16 19:29 UTC, liamdebeasi approved these changes

2022-12-16 19:29 UTC, sean-perkins approved these changes

2022-12-16 19:44 UTC, amandaejohnston commented
@sean-perkins Item tests are handled here: https://github.com/ionic-team/ionic-framework/pull/26471

2022-12-20 16:45 UTC, merged