2693 label func
ionic-team/ionic-framework pull request #26505
Opened 2022-12-16 19:11 UTC by liamdebeasi

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue URL: 

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-01-03 17:03 UTC, amandaejohnston requested changes

2023-01-03 19:22 UTC, amandaejohnston commented on core/src/components/select/select.scss
> +  @include transform(rotate(180deg));
Aha, saw you already addressed this one: https://github.com/ionic-team/ionic-framework/pull/26519 Disregard!

2023-01-04 13:58 UTC, liamdebeasi commented on core/src/components/select/select.scss
> +:host(.select-expanded.select-label-placement-floating) .label-text-wrapper,
Yes, this is intentional. See https://material-components.github.io/material-components-web-catalog/#/component/select

2023-01-04 14:45 UTC, amandaejohnston approved these changes

2023-01-04 20:25 UTC, liamdebeasi commented
Updated the screenshots to account for the new Playwright version from `main`

2023-01-04 21:53 UTC, merged