fix(react/vue): properly switch ionicon based on the mode when ios/md is set
ionic-team/ionic-framework pull request #26924
Opened 2023-03-07 19:03 UTC by brandyscarney

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue URL: closes #26207

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-03-09 20:20 UTC, amandaejohnston approved these changes

2023-03-10 14:03 UTC, liamdebeasi commented on packages/vue/src/components/IonIcon.ts
> +      const config = getConfig();
`getConfig` can return null, so we should have a fallback for when that is the case: https://github.com/ionic-team/ionic-framework/blob/27a5356fa2b72073d565e9d6f527107869faa3ee/packages/vue/src/utils.ts#L66

2023-03-10 14:04 UTC, liamdebeasi requested changes
Can we write tests to verify this behavior in the react and vue packages?

2023-03-10 14:04 UTC, liamdebeasi commented on packages/react/src/components/IonIcon.tsx
> +    const config = getConfig();
`getConfig` can return null so we should have a fallback for when that is the case: https://github.com/ionic-team/ionic-framework/blob/27a5356fa2b72073d565e9d6f527107869faa3ee/packages/react/src/components/utils/index.tsx#L31

2023-03-14 18:42 UTC, liamdebeasi approved these changes

2023-03-14 19:03 UTC, merged