fix(select): inherit white-space in select-text to allow wrapping
ionic-team/ionic-framework pull request #26973
Opened 2023-03-15 19:17 UTC by brandyscarney

This is a recreation of https://github.com/ionic-team/ionic-framework/pull/26914 in order to run our screenshots

-----

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue URL: 

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-03-17 15:41 UTC, brandyscarney commented
@liamdebeasi Can you take a look at approving this PR? Same as the other one I just ran the screenshot action. All the screenshots are updated to include the wrapping example.

2023-03-17 15:46 UTC, liamdebeasi requested changes

2023-03-20 18:34 UTC, liamdebeasi commented on core/src/components/select/test/basic/index.html
> +            <ion-select id="hairColor" value="brown" ok-text="Okay" cancel-text="Dismiss" class="ion-text-wrap">
I think we should remove the test modifications made in this PR and add the proposed tests

2023-03-22 14:29 UTC, brandyscarney commented
@liamdebeasi This is ready for another review! I updated to include a test just for the wrapping.

2023-03-22 14:37 UTC, liamdebeasi requested changes
Fixes look good! Just a couple clean up items and this is good to merge. Great job!

2023-03-22 14:37 UTC, liamdebeasi commented on core/src/components/select/test/wrapping/select.e2e.ts
> +    // TODO update label for v7
Can we make a tech debt ticket for this? See the "Technical Debt" section of the "Pull Requests" process in Notion.

2023-03-22 14:37 UTC, liamdebeasi commented on core/src/components/select/test/basic/select.e2e.ts-snapshots/select-action-sheet-diff-ios-ltr-Mobile-Chrome-linux.png
Are we able to remove these old screenshot diffs? Easiest might be to revert the specific commits.

2023-03-22 17:59 UTC, brandyscarney commented on core/src/components/select/test/basic/select.e2e.ts-snapshots/select-action-sheet-diff-ios-ltr-Mobile-Chrome-linux.png
Should be good now. I had to checkout the files from `main` because they were changed twice so the revert wouldn't work.

2023-03-23 17:05 UTC, liamdebeasi approved these changes
Thank you!!

2023-03-24 14:53 UTC, merged