fix(menu): update location when dynamically changing side or doc dir
ionic-team/ionic-framework pull request #27079
Opened 2023-03-31 20:56 UTC by thetaPC

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
  - Some docs updates need to be made in the `ionic-docs` repo, in a separate PR. See the [contributing guide](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#modifying-documentation) for details.
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

- When the document direction is dynamically changed, the menu does not switch to the correct position. For example, `<ion-menu side='start'>` will always be on the left side regardless of direction.
- When the side property is dynamically changed, the animation starts in the middle of the screen instead of off screen.

Issue URL: resolves #25601 #19489 

## What is the new behavior?

- Animation is smooth regardless of side property or document direction being dynamically change. 
- Menu appears on the correct side based on document direction when dynamically updated.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

N/A

2023-04-03 17:36 UTC, thetaPC commented
@amandaejohnston I've updated the references and the PR is ready to go.

2023-04-04 14:50 UTC, amandaejohnston requested changes
This looks great! Just had a small request on the tests.

2023-04-04 14:50 UTC, amandaejohnston commented on core/src/components/menu/test/basic/menu.e2e.ts
> +  test('should render on the correct side when side is changed dynamically', async ({ page }) => {
Could we also add `skip.mode('md')` or `skip.mode('ios')` to both tests? These checks aren't mode-dependent, and the more screenshots we can trim down, the better. You can also just manually delete the screenshots for the mode you skipped.

2023-04-04 18:39 UTC, amandaejohnston approved these changes
Nice work!

2023-04-04 19:25 UTC, merged