test(range): use modern form syntax
ionic-team/ionic-framework pull request #27188
Opened 2023-04-13 04:33 UTC by sean-perkins

## What is the current behavior?

The legacy range tests do not specify `legacy="true"`. Inversely, the modern tests are not using the modern form syntax.

Issue URL: N/A

## What is the new behavior?

- Legacy range tests specify `legacy="true"`
- Modern range tests use modern form control syntax

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-04-13 04:39 UTC, sean-perkins commented
The updated syntax/screenshots appear to have caught a visual bug with the knob positioning/clipping when used without a label. I'll circle back to confirming that + opening a bug report if that is the case.

2023-05-09 15:56 UTC, thetaPC requested changes
I didn't review the tests since I expect them to change after resolving the conflicts.

2023-06-23 15:04 UTC, sean-perkins commented
Ok, I dug into this further and I am no longer concerned with that screenshot diff. The reason for clipping is that the bounding box does not contain the knob overflow:

![CleanShot 2023-06-23 at 11 02 09](https://github.com/ionic-team/ionic-framework/assets/13732623/ffeb94cb-c895-49f9-82b5-cf8f55a05a76)

So when playwright captures the element screenshot, it results in the clipped appearance. In an application, this should not occur (unless they have a container with `overflow: hidden` directly around the `ion-range`. 

Once CI passes, I think this is ready for review to see if the team is in favor of the approach for solving this bug. Open to other ideas/suggestions as well 👍

2023-06-23 17:04 UTC, thetaPC commented on core/src/components/range/test/label/range.e2e.ts-snapshots/range-no-items-no-label-ios-ltr-Mobile-Chrome-linux.png
Could we wrap the range in a container through the test file? The container could have padding. If we take a screenshot of the container, it should show the entire knob. Would that work?

2023-07-12 18:26 UTC, thetaPC reviewed
Everything looks good. One thing that I noticed is that the focused blue circle is getting clipped when there isn't an icon when moving the knob either far right or far left.

Is it possible to have the focused circle to render on top?

https://github.com/ionic-team/ionic-framework/assets/13530427/525f530f-44ac-49ea-9796-c54a6594738a

2023-07-12 19:40 UTC, sean-perkins commented
@thetaPC here's an approach we could take:

https://github.com/ionic-team/ionic-framework/assets/13732623/9d958180-aedb-4f8c-9a50-606b7cc8b636

It requires bumping the default padding from `14px` to `18px` on MD. This does cause the usage without a start icon or label to be padded an additional 4px to offset for the focus ring.

Thoughts? I think if we do this, we should target for a minor release since we are adjusting default values in pursuit of correcting visual issues.

2023-07-12 21:04 UTC, thetaPC commented
> @thetaPC here's an approach we could take:
> Kapture.2023-07-12.at.15.39.11.mp4
> 
> It requires bumping the default padding from `14px` to `18px` on MD. This does cause the usage without a start icon or label to be padded an additional 4px to offset for the focus ring.
> 
> Thoughts? I think if we do this, we should target for a minor release since we are adjusting default values in pursuit of correcting visual issues.

2 pixels feels like a lot. I do agree that if we make this change then it should be a minor.

I'm leaning towards starting a with the rest of the team for their thoughts. Otherwise, your solution works but wondering if it could lead to issues later.

2023-09-19 21:33 UTC, sean-perkins commented
Closing this PR in favor of https://github.com/ionic-team/ionic-framework/pull/28199

2023-09-19 21:33 UTC, closed without merging