feat(segment, segment-button): Update segment value property to accept numbers
ionic-team/ionic-framework pull request #27222
Opened 2023-04-17 21:44 UTC by Morritz

Issue number: #27221

---------

## What is the current behavior?

The value property of the segment component in Ionic Framework currently only accepts string values.

## What is the new behavior?

This pull request updates the "value" property of the segment component to accept a union of string and number types. This allows for more versatile data input in the segment component, particularly for users who work with numerical data.

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

N/A

2023-04-17 21:49 UTC, JakubCzura commented
So interesting feature. It will be good if they merge it.

2023-04-18 13:11 UTC, liamdebeasi commented
Thanks for the request and PR! I think this would be a good feature to add to Ionic. The next step for us is to create a design document of how the feature will work/be implemented. This design process allows us to a) discuss the feature so there is consensus and b) ensure that the API is well designed.

I have created the design document internally, and the team will be looking at it soon. If the design document gets approved, then someone will review your PR and potentially request changes. Let me know if you have questions.

2023-04-24 18:58 UTC, liamdebeasi requested changes
The team has completed our design document, so we are looking to move forward with this PR. I left a requested change below.

One other thing is since this is a feature, we'll need to merge into the `feature-7.1` branch instead of `main`. Let me know if you have any questions!

2023-04-24 18:58 UTC, liamdebeasi commented on core/src/components/segment/segment-interface.ts
> +export type SegmentValue = string | number;
The `SegmentValue` interface needs to be exported from `packages/vue/src/index.ts`, `angular/src/index.ts`, and `packages/react/src/components/index.ts` too.

2023-05-24 02:01 UTC, sean-perkins commented
Rebased the branch against `feature-7.1`, this is ready for new reviews.

2023-05-24 13:41 UTC, liamdebeasi approved these changes
Thank you!

2023-05-24 14:07 UTC, amandaejohnston approved these changes

2023-05-24 14:07 UTC, merged