fix(tab-button): use darker text to pass a11y
ionic-team/ionic-framework pull request #27355
Opened 2023-05-02 20:47 UTC by brandyscarney

Issue number: N/A

---------

- Changes the default Material Design tab color to `$text-color-step-350` or `#a6a6a6`
- Changes the default iOS tab color to `$text-color-step-400` or `#999999`
- Removes the axe skip in the e2e test

These were the minimum color changes needed to pass axe.

2023-05-03 00:19 UTC, thetaPC requested changes
LGTM, but I would like to review the screenshots too. There shouldn't be any issues. I've just learned to not trust screenshots.

2023-05-03 18:26 UTC, mapsandapps approved these changes

2023-05-03 18:49 UTC, sean-perkins commented on core/src/themes/ionic.theme.default.md.scss
> +$tabbar-md-color:                           var(--ion-tab-bar-color, $text-color-step-350) !default;
Shouldn't we be seeing some screenshot diffs for MD because of this?

2023-05-10 15:12 UTC, thetaPC approved these changes
LGTM

2023-05-10 15:17 UTC, liamdebeasi commented
Discussed with Brandy offline, but I manually removed the MD screenshots in https://github.com/ionic-team/ionic-framework/pull/27355/commits/4c40f185f4460197494a1207698e55760f24963e so they can be regenerated. The diff for the MD screenshots is too small to be detected with our current diff threshold of 0.1. However, I am hesitant to lower the threshold below 0.1 because we risk getting false positives with our screenshots.

2023-05-10 15:18 UTC, liamdebeasi approved these changes
Good to merge once tests pass/screenshots are updated.

2023-05-11 20:53 UTC, merged