test(tab-button): add focus state screenshots
ionic-team/ionic-framework pull request #27731
Opened 2023-06-30 15:29 UTC by liamdebeasi

Issue number: #

---------

## What is the current behavior?

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-07-05 15:10 UTC, brandyscarney requested changes
I'm not really seeing a difference between the translucent and non-translucent tabs - should we add some divs behind them or something?

2023-07-05 17:59 UTC, liamdebeasi commented on core/src/components/tab-button/test/states/tab-button.e2e.ts
> +        await expect(tabBar).toHaveScreenshot(screenshot('tab-bar-focus-default-theme-no-translucency'));
Fixed in https://github.com/ionic-team/ionic-framework/pull/27731/commits/72186539be532c14450271e2004fa833e4c57e42

2023-07-05 17:59 UTC, liamdebeasi commented on core/src/components/tab-button/test/states/tab-button.e2e.ts
> +        await expect(tabBar).toHaveScreenshot(screenshot('tab-bar-focus-custom-theme-no-translucency'));
Fixed in https://github.com/ionic-team/ionic-framework/pull/27731/commits/bd1105cb44cb52c4da38d3e68fe98af391774de4

2023-07-05 18:05 UTC, liamdebeasi commented
I added a dark background color in https://github.com/ionic-team/ionic-framework/pull/27731/commits/af08359fb0f3367875241bbdd1d7eee85bef1495. Screenshots are updating now.

2023-07-06 16:03 UTC, brandyscarney approved these changes

2023-07-06 16:20 UTC, merged