feat(searchbar): add name property
ionic-team/ionic-framework pull request #27737
Opened 2023-07-02 16:17 UTC by NicoDos

Issue number: #27675

---------

## What is the current behavior?
There is no name property to ion-search

## What is the new behavior?
- Added name property to ion-search

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2023-07-05 12:51 UTC, liamdebeasi commented
Thanks for the PR! We appreciate you contributing to Ionic. In terms of next steps, the team needs to do some design work to make sure this `name` property aligns with the `name` properties in other components. Once that is complete, someone from the team will do a code review and request any changes. Let me know if you have any questions.

2023-07-12 19:52 UTC, sean-perkins requested changes
I only have one outstanding change + re-generating the proxies after syncing with `main`.

2023-07-12 19:52 UTC, sean-perkins commented on core/src/components/searchbar/searchbar.tsx
> +  @Prop() name?: string;
We'd like to a follow a similar architecture that we've done here with `ion-radio`: https://github.com/ionic-team/ionic-framework/blob/3bd1d7e1e501ca82830de1b375b38135ab4f6311/core/src/components/radio/radio.tsx#L62

Basically, defaulting the value of `name` to the `inputId`. 

The `inputId` would be a new member of this class:

```ts
private inputId = `ion-searchbar-${searchbarIds++}`;
```

where `let searchbarIds = 0;` is added outside of the search bar class, at the top or bottom of this file.

2023-07-13 02:08 UTC, sean-perkins commented
Ok - this PR is ready for a team review. `feature-7.2.` is fairly behind `main`, so I'll wait to changing the target branch until we get that branch synced.

2023-07-13 02:30 UTC, sean-perkins approved these changes

2023-07-17 15:43 UTC, merged