Fw 4765
ionic-team/ionic-framework pull request #27883
Opened 2023-07-28 15:00 UTC by liamdebeasi

Issue number: #

---------

## What is the current behavior?

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-07-28 15:13 UTC, liamdebeasi commented on packages/angular/common/src/utils.ts
> +// TODO: Is there a way we can grab this from angular-component-lib instead?
So the main problem here is these functions are originally defined in `src/angular-component-lib` which is treated as a separate module than what we are in currently. Former is in `@ionic/angular` latter is in `@ionic/angular/common`.

I could export these functions from `@ionic/angular`, but then they'd be public API which seems strange. I could also have these files be generated in the common directory, but then that means the autogenerated lazy loaded components will be added to the common directory too.

Given that these functions do not often change, the best approach I have right now is to copy it over. Open to other ideas!

2023-07-28 19:41 UTC, liamdebeasi commented
I'm experimenting with a simpler way of doing this. Going to move back to a draft for now.

2023-08-03 23:29 UTC, thetaPC approved these changes
LGTM

2023-08-04 16:38 UTC, sean-perkins requested changes
Not related to your changes directly, but we should fix this documentation mistake while we are here.

2023-08-04 16:38 UTC, sean-perkins commented on packages/angular/common/src/overlays/popover.ts
> +   * Emitted after the popover has presented. Shorthand for ionPopoverWillDismiss.
```suggestion
   * Emitted after the popover has presented. Shorthand for ionPopoverDidPresent.
```

2023-08-04 18:49 UTC, sean-perkins approved these changes

2023-08-04 20:55 UTC, merged