Fw 4764
ionic-team/ionic-framework pull request #27885
Opened 2023-07-28 16:54 UTC by liamdebeasi

Issue number: #

---------

## What is the current behavior?

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-07-28 16:55 UTC, liamdebeasi commented on packages/angular/common/src/utils.ts
> +// TODO: Is there a way we can grab this from angular-component-lib instead?
See https://github.com/ionic-team/ionic-framework/pull/27883#discussion_r1277684368

2023-08-03 23:31 UTC, thetaPC approved these changes
LGTM

2023-08-04 16:39 UTC, sean-perkins requested changes
Similar feedback to popover. Implementation changes look good. Just one minor documentation tweak.

2023-08-04 16:39 UTC, sean-perkins commented on packages/angular/common/src/overlays/modal.ts
> +   * Emitted after the modal has presented. Shorthand for ionModalWillDismiss.
```suggestion
   * Emitted after the modal has presented. Shorthand for ionModalDidPresent.
```

2023-08-04 18:49 UTC, sean-perkins approved these changes

2023-08-04 19:45 UTC, merged