feat(toast): add part for button cancel
ionic-team/ionic-framework pull request #27921
Opened 2023-08-03 03:38 UTC by luisbytes

Issue number: [#27920](https://github.com/ionic-team/ionic-framework/issues/27920)

---------

## What is the current behavior?
It is not possible to style the buttons with the cancel role in a toast since it uses shadow DOM and there are no exposed parts or CSS variables for the cancel buttons.

## What is the new behavior?

- Exposes the following part of a toast: `button with rol cancel`
- Update the e2e toast test to check if the `button-cancel` part is exposed
-

## Does this introduce a breaking change?

- [X] Yes
- [ ] No

Change the css shadow part for all buttons added to a toast with the cancel role from 'button' to 'button-cancel'.  

## Other information

2023-08-03 13:55 UTC, liamdebeasi commented
Thanks for the PR! We appreciate you contributing to Ionic. I discussed this with the team, and we think this is a good feature to add. Our next step is to do a design document to make sure we are implementing this feature in a way that addresses the original use case.

Once that is done, someone from the team will review this PR and get it ready to merge. Let me know if you have any questions.

2023-08-09 14:41 UTC, liamdebeasi requested changes
Overall this looks good! A few small changes.

2023-08-09 14:41 UTC, liamdebeasi commented on core/src/components/toast/toast.tsx
> +  return isCancel(button.role) ? 'button-cancel' : 'button';
```suggestion
  return isCancel(button.role) ? 'button cancel' : 'button';
```

For parts with state/modifiers, we should add it as multiple parts. This way the cancel button still matches the `button` part in addition to `button cancel`.

2023-08-09 14:41 UTC, liamdebeasi commented on core/src/components/toast/toast.tsx
> + * @part button-cancel - Any button element with role "cancel" that is displayed inside of the toast.
Same as my other comment: Let's call this `button cancel`
```suggestion
 * @part button cancel - Any button element with role "cancel" that is displayed inside of the toast.
```

2023-08-09 14:41 UTC, liamdebeasi commented on core/src/components/toast/test/buttons/toast.e2e.ts
> +      await expect(buttonCancel).toHaveAttribute('part', 'button-cancel');
Can we make this a spec test? E2E tests fire up an entire browser instance which is slow and not necessary for the kind of validation we are trying to do.

Here's an example of a spec test in Ionic: https://github.com/ionic-team/ionic-framework/blob/1cf1eca00239f3e98854466116e42f9a2e7b4590/core/src/components/select/test/select.spec.tsx#L2

2023-08-09 14:42 UTC, liamdebeasi requested changes
Can you also rebase this off `feature-7.3`? This is the next minor release we are targeting.

2023-08-09 20:47 UTC, luisbytes commented
@liamdebeasi Hello, I'm ready with the changes you suggested. I failed to do the rebase.

2023-08-10 16:26 UTC, merged

2023-08-10 16:26 UTC, liamdebeasi commented
Merged. Thank you very much!

2023-08-10 18:00 UTC, luisbytes commented
@liamdebeasi Thank you, I hope to contribute more to the community.