Fw 4612
ionic-team/ionic-framework pull request #28311
Opened 2023-10-09 18:39 UTC by liamdebeasi

Issue number: #

---------

## What is the current behavior?

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-10-09 23:33 UTC, thetaPC requested changes

2023-10-10 14:45 UTC, liamdebeasi commented on packages/angular/test/base/src/app/app.component.css
Not sure what you mean - the file was deleted in the diff?

2023-10-10 15:19 UTC, thetaPC commented on packages/angular/test/base/src/app/app.component.css
It's showing as an empty file instead of a deleted one.
![Screenshot 2023-10-10 at 8 18 58 AM](https://github.com/ionic-team/ionic-framework/assets/13530427/fd5d27c8-b070-48f9-b56f-51481e9be6aa)

2023-10-10 15:26 UTC, liamdebeasi commented on packages/angular/test/base/src/app/app.component.css
The red means that it was deleted. The file that was deleted was empty though. The `app.component.ts` diff also shows that we removed a reference to the file: https://github.com/ionic-team/ionic-framework/pull/28311/files#diff-f489c71da69710fe7957173822f2d6e8dea4bb8660b6bd44ed2efa41ecd8accb

2023-10-10 15:27 UTC, liamdebeasi commented on packages/angular/test/base/src/app/app.component.css
Screenshot of the linked diff since GitHub didn't always load it on my end: 
![image](https://github.com/ionic-team/ionic-framework/assets/2721089/34fdd9f6-1e94-4636-af99-0837f21eb91b)

2023-10-10 15:29 UTC, thetaPC commented on packages/angular/test/base/src/app/app.component.css
Ah, that makes sense. Thank you!

2023-10-10 15:31 UTC, thetaPC approved these changes
LGTM

2023-10-10 16:28 UTC, sean-perkins approved these changes

2023-10-10 17:06 UTC, merged