fix(item): apply safe area to proper side regardless of direction
ionic-team/ionic-framework pull request #28403
Opened 2023-10-24 15:57 UTC by mapsandapps

Issue number: Internal

---------

## What is the current behavior?

The safe area for Item would change sides when the direction changed. e.g., if the safe area padding should be on the left, it would be on the left when the direction was LTR but would be on the right when the direction was RTL. It should always be on the left.

## What is the new behavior?

- The left safe area padding is on the left side of Item whether the direction is LTR or RTL.
- The right safe area padding is on the right side of Item whether the direction is LTR or RTL.
- There's now a screenshot test for left and right padding for both directions.

Note: There is a separate ticket for updating the safe area padding for ion-item-divider.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-10-27 14:53 UTC, amandaejohnston approved these changes

2023-10-27 14:53 UTC, amandaejohnston commented on core/src/components/item/item.scss
> +    padding-left:var(--inner-padding-start);
```suggestion
    padding-right: calc(var(--ion-safe-area-right, 0px) + var(--inner-padding-end));
    padding-left: var(--inner-padding-start);
```

2023-10-27 15:17 UTC, brandyscarney commented on core/src/components/item/item.scss
> +
Was the top and bottom padding removed on purpose?

```scss
@include @padding(0, null, 0); 
```

2023-10-27 15:28 UTC, brandyscarney requested changes
This is looking good, just a couple of things I found that I wanted to bring up!

2023-10-27 15:28 UTC, brandyscarney commented on core/src/components/item/item.scss
> +    padding-right: calc(var(--padding-start) + var(--ion-safe-area-right, 0));
```suggestion
    padding-right: calc(var(--padding-start) + var(--ion-safe-area-right, 0px));
```

2023-10-27 15:28 UTC, brandyscarney commented on core/src/components/item/test/basic/item.e2e.ts-snapshots/safe-area-ios-rtl-Mobile-Chrome-linux.png
I think we might be applying the `--ion-safe-area-left` to the wrong element here. This might have been a problem prior to this PR but maybe we should look into it? 

If you notice on the LTR test the bottom border extends the full width to the right, even though `--ion-safe-area-right` is set to `10px`: 

![image](https://github.com/ionic-team/ionic-framework/assets/6577830/ffa0e79f-014d-4b22-98fa-b66fea01c781)

When flipped, the bottom border is not extending fully to the left edge:

![image](https://github.com/ionic-team/ionic-framework/assets/6577830/9f388d4d-35f9-432b-9897-b397c96d633c)

Happy to bring this up for team discussion to see if we should make this a separate issue!

2023-10-30 14:51 UTC, liamdebeasi commented
Removing myself as a reviewer. I'm getting added as a code-owner due the screenshot changes, but I think Amanda and Brandy have this covered 😄

2023-10-31 17:29 UTC, mapsandapps commented on core/src/components/item/test/basic/item.e2e.ts-snapshots/safe-area-ios-rtl-Mobile-Chrome-linux.png
I think this was actually a mistake with this PR, not from before. Thanks for catching it!

2023-11-01 21:33 UTC, brandyscarney reviewed
The code itself looks good, great work! Just some minor feedback on the test.

2023-11-01 21:33 UTC, brandyscarney commented on core/src/components/item/test/basic/item.e2e.ts
> +            --ion-safe-area-right: 10px;
```suggestion
            --ion-safe-area-left: 40px;
            --ion-safe-area-right: 20px;
```

Nit pick but we have used these values in a few other places, could we update them to match? 

https://github.com/ionic-team/ionic-framework/blob/b7d1a5c86bf81b0808c343f35ba64214dba39e6f/core/src/components/list-header/test/basic/list-header.e2e.ts#L29-L30
https://github.com/ionic-team/ionic-framework/blob/b7d1a5c86bf81b0808c343f35ba64214dba39e6f/core/src/components/fab/test/safe-area/fab.e2e.ts#L11-L12

2023-11-01 21:33 UTC, brandyscarney commented on core/src/components/item/test/basic/item.e2e.ts
> +      await expect(list).toHaveScreenshot(screenshot('safe-area'));
```suggestion
      await expect(list).toHaveScreenshot(screenshot('item-safe-area'));
```

The test name should start with the component name. You will need to delete the screenshots that were added and run the update action again or rename them.

2023-11-02 13:33 UTC, brandyscarney approved these changes

2023-11-02 14:31 UTC, merged