refactor(angular): loading controller uses correct core instance
ionic-team/ionic-framework pull request #28543
Opened 2023-11-16 15:45 UTC by mapsandapps

Issue number: Internal

---------

## What is the current behavior?
As a takeaway from our learning session about a menuController bug in Ionic Angular, the team would like to update our other providers to use the same architecture as the menuController to prevent this kind of issue from happening again in the future.

We also noticed that the common provider does not provide much value and it's easier to just have two separate implementations in `src` and `standalone`. (There wasn't much code we could de-duplicate)

## What is the new behavior?

- Removed the common loading provider in favor of separate ones in src/standalone

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-11-16 20:53 UTC, sean-perkins requested changes

2023-11-16 20:53 UTC, sean-perkins commented on packages/angular/standalone/src/providers/loading-controller.ts
> +import { loadingController } from '@ionic/core';
This is referencing the lazy instance of the loading controller, which is not desired. These imports should come from `@ionic/core/components`.

2023-11-17 16:22 UTC, thetaPC commented
@mapsandapps is this ready to review?

2023-11-17 16:48 UTC, mapsandapps commented
@thetaPC yep!

2023-11-17 16:55 UTC, sean-perkins approved these changes

2023-11-17 21:27 UTC, merged