Fw 5575
ionic-team/ionic-framework pull request #28689
Opened 2023-12-11 20:36 UTC by liamdebeasi

Issue number: #

---------

## What is the current behavior?

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-12-12 19:02 UTC, amandaejohnston requested changes

2023-12-12 19:02 UTC, amandaejohnston commented on BREAKING.md
(Threading) I noticed a couple of oddities with the datetime `custom` test, compared to `main` 🤔

The time picker popover no longer has its fade background styled:
![missing fade bg](https://i.gyazo.com/2057aeee04086c266e8743586178b696.png)

And on the wheel picker datetime, when scrolling the options, there is a delay before the active item styles apply to the newly selected item (most obvious when using the scroll wheel):

https://github.com/ionic-team/ionic-framework/assets/90629384/89497461-2163-49fe-b46b-260e9bcedbe8

2023-12-12 23:03 UTC, liamdebeasi commented on BREAKING.md
First issue is fixed in https://github.com/ionic-team/ionic-framework/pull/28689/commits/e4797a46d2a5672bdcffc7eea6199c758af5aaca.

The second issue is working as intended. The old behavior added the Shadow Part every time the scroll listener fired and the centered item changed: https://github.com/ionic-team/ionic-framework/blob/8ee23d20d5cc7419ce15f047b92d2f826d3eb681/core/src/components/picker-column-internal/picker-column-internal.tsx#L206

However, since the shadow part is now set from `ion-datetime this part is only set when the value of the picker column changes which is done in a timeout: https://github.com/ionic-team/ionic-framework/blob/8ee23d20d5cc7419ce15f047b92d2f826d3eb681/core/src/components/picker-column-internal/picker-column-internal.tsx#L332

2023-12-13 15:24 UTC, amandaejohnston commented on BREAKING.md
We discussed the second issue in Slack and agreed to wait and see if we get feedback on it before making changes.

2023-12-13 15:24 UTC, amandaejohnston approved these changes

2023-12-13 18:03 UTC, merged