docs(angular test app): include instructions for updating nightly build
ionic-team/ionic-framework pull request #28948
Opened 2024-01-31 20:00 UTC by mapsandapps

Issue number: None

---------

## What is the current behavior?

People adding a new Angular test app don't know they need to update the Stencil nightly build.

## What is the new behavior?

- Documentation exists for adding a new Angular version to the Stencil nightly build when creating a new Angular test app..

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This is related to #28945

2024-01-31 20:28 UTC, thetaPC requested changes

2024-01-31 20:28 UTC, thetaPC commented on packages/angular/test/README.md
> +11. Commit these changes and push.
```suggestion
10. Open `./github/workflows/stencil-nightly.yml` and find the `test-angular-e2e` job.
11. Repeat steps 8 and 9.
12. Commit these changes and push.
```

I would like to keep the look consistent between step 7 and 10.

2024-01-31 23:40 UTC, thetaPC approved these changes
LGTM

2024-02-01 15:43 UTC, liamdebeasi approved these changes

2024-02-01 16:00 UTC, merged