Fw 2876
ionic-team/ionic-framework pull request #28993
Opened 2024-02-07 16:23 UTC by brandyscarney

Issue number: resolves #

---------

## What is the current behavior?

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-02-07 19:22 UTC, brandyscarney commented on core/src/components/item/test/disabled/item.e2e.ts-snapshots/item-disabled-diff-ios-ltr-Mobile-Chrome-linux.png
This screenshot is updated due to textarea being removed.

2024-02-08 14:16 UTC, liamdebeasi approved these changes

2024-02-08 18:27 UTC, merged

2024-02-08 18:46 UTC, thetaPC requested changes

2024-02-08 18:46 UTC, thetaPC commented on core/src/components/textarea/textarea.ios.scss
I'm still seeing an [instance](https://github.com/ionic-team/ionic-framework/blob/0c667612c6600e7ca31f33873cdea612210411c2/core/src/components/textarea/textarea.ios.scss#L31) of `.legacy-textarea` that needs to be removed.

2024-02-08 18:46 UTC, thetaPC commented on core/src/components/textarea/textarea.md.scss
I'm still seeing an [instance](https://github.com/ionic-team/ionic-framework/blob/0c667612c6600e7ca31f33873cdea612210411c2/core/src/components/textarea/textarea.md.scss#L52) of `.legacy-textarea` that needs to be removed.

2024-02-08 18:46 UTC, thetaPC commented
Shoot, I didn't realize it was merged in while I was reviewing. Apologies for being slow.

2024-02-08 23:04 UTC, brandyscarney commented
I'm not sure how I missed those when I searched for `legacy` ha. Added a PR to remove them here: https://github.com/ionic-team/ionic-framework/pull/29006

You got added as a reviewer due to being a codeowner when I merged in this PR: https://github.com/ionic-team/ionic-framework/pull/28994 but they both had approvals so I merged this, sorry!