feat(date-time): add Overlay roles
ionic-team/ionic-framework pull request #29221
Opened 2024-03-26 13:06 UTC by Rahul-28

Issue number: resolves #28298

---------

## What is the current behavior?

 - the ion-datetime didn't provide a role(source trigger for closing the overlay) on default buttons while closing parent overlay

## What is the new behavior?

- ion-datetime provides a role to while closing the parent overlay

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-03-28 13:17 UTC, liamdebeasi requested changes
Thanks for making this PR!

2024-03-28 13:17 UTC, liamdebeasi commented on core/src/components/datetime/test/overlay-roles/index.html
> +      }
```suggestion
```

These styles aren't needed to test the modal

2024-03-28 13:17 UTC, liamdebeasi commented on core/src/components/datetime/test/overlay-roles/index.html
> +            </ion-datetime>
```suggestion
            <ion-datetime show-default-buttons="true"></ion-datetime>
```

The additional props are not needed to test this

2024-03-28 13:17 UTC, liamdebeasi commented on core/src/components/datetime/test/overlay-roles/index.html
> +      });
```suggestion
```

Since we are removing the dark theme toggle we can remove this too.

2024-03-28 13:17 UTC, liamdebeasi commented on core/src/components/datetime/test/overlay-roles/index.html
> +          </ion-popover>
```suggestion
```

These are not required to test to the modal

2024-04-03 13:35 UTC, Rahul-28 commented
hey @liamdebeasi the lint issues are fixed can you please review my changes

2024-04-03 18:26 UTC, liamdebeasi approved these changes
Tested, and this works great. Thank you!

2024-04-03 19:21 UTC, merged

2024-04-03 19:22 UTC, liamdebeasi commented
Merged, thanks again!