chore(): add updated snapshots
ionic-team/ionic-framework pull request #29434
Opened 2024-05-01 14:31 UTC by brandyscarney

Issue number: resolves #

---------

## What is the current behavior?

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-05-01 19:27 UTC, liamdebeasi requested changes

2024-05-01 19:27 UTC, liamdebeasi commented on core/src/components/picker/test/basic/picker.e2e.ts-snapshots/picker-popover-diff-md-ltr-Mobile-Firefox-linux.png
Are there buttons on the page for this test? I see a 1px diff above the picker.

2024-05-01 19:27 UTC, liamdebeasi commented on core/src/components/popover/test/basic/popover.e2e.ts-snapshots/popover-basic-basic-popover-ios-rtl-Mobile-Chrome-linux.png
Looks like this test is missing a full width button

2024-05-01 19:27 UTC, liamdebeasi commented on core/src/components/popover/test/size/popover.e2e.ts-snapshots/popover-size-ios-ltr-Mobile-Safari-linux.png
Why is the bottom popover running up against the top popover?

2024-05-01 19:27 UTC, liamdebeasi commented on core/src/components/toast/test/basic/toast.e2e.ts-snapshots/toast-color-ios-ltr-Mobile-Chrome-linux.png
Is this diff due to an underlying button too? Same question for the other toast screenshots.

2024-05-01 19:27 UTC, liamdebeasi commented on core/src/components/toast/test/basic/toast.e2e.ts-snapshots/toast-translucent-color-ios-ltr-Mobile-Chrome-linux.png
Looks like the translucency is broken here

2024-05-01 19:41 UTC, brandyscarney commented on core/src/components/toast/test/basic/toast.e2e.ts-snapshots/toast-translucent-color-ios-ltr-Mobile-Chrome-linux.png
What do you mean? You are supposed to see the button behind it, no?

2024-05-01 19:49 UTC, brandyscarney commented on core/src/components/toast/test/basic/toast.e2e.ts-snapshots/toast-color-ios-ltr-Mobile-Chrome-linux.png
Yeah it's due to the button behind the toast. I honestly hate these tests and wish we just captured the toast itself lol. If you use the "Swipe" comparison you can see the button behind the toast gets larger.

2024-05-01 19:56 UTC, brandyscarney commented on core/src/components/popover/test/size/popover.e2e.ts-snapshots/popover-size-ios-ltr-Mobile-Safari-linux.png
The popover width is dependent on the button width, so the smaller width of the buttons is causing the top popover to be taller. I can adjust the button padding to make it similar to the older way.

2024-05-01 20:01 UTC, brandyscarney commented on core/src/components/picker/test/basic/picker.e2e.ts-snapshots/picker-popover-diff-md-ltr-Mobile-Firefox-linux.png
Yes this test is opened by a button:

<img width="327" alt="Screenshot 2024-05-01 at 4 00 23 PM" src="https://github.com/ionic-team/ionic-framework/assets/6577830/149c0133-f220-4f16-accb-763da858a1bc">

2024-05-01 20:16 UTC, brandyscarney commented on core/src/components/popover/test/basic/popover.e2e.ts-snapshots/popover-basic-basic-popover-ios-rtl-Mobile-Chrome-linux.png
Fixed by https://github.com/ionic-team/ionic-framework/pull/29434/commits/8bdd67a053a267858ac7a70fcaac4cdf5221b980

2024-05-01 20:17 UTC, brandyscarney commented on core/src/components/popover/test/size/popover.e2e.ts-snapshots/popover-size-ios-ltr-Mobile-Safari-linux.png
Fixed by https://github.com/ionic-team/ionic-framework/pull/29434/commits/8bdd67a053a267858ac7a70fcaac4cdf5221b980

2024-05-01 20:28 UTC, liamdebeasi commented on core/src/components/toast/test/basic/toast.e2e.ts-snapshots/toast-translucent-color-ios-ltr-Mobile-Chrome-linux.png
In the original screenshot the backdrop filter blur applies, blurring the button underneath it. The new screenshot does not have the blurred background effect.

![image](https://github.com/ionic-team/ionic-framework/assets/2721089/1cb698cb-25a1-458b-bda8-233991a2a379)

2024-05-01 20:32 UTC, liamdebeasi commented on core/src/components/toast/test/basic/toast.e2e.ts-snapshots/toast-color-ios-ltr-Mobile-Chrome-linux.png
We are taking a screenshot of the toast itself, but the toast overlays the rest of the page so sadly the button shows up. Most of these tests could probably use `setContent` to render just the toast without anything else on the page.

2024-05-01 20:37 UTC, brandyscarney commented on core/src/components/toast/test/basic/toast.e2e.ts-snapshots/toast-color-ios-ltr-Mobile-Chrome-linux.png
Sorry that's what I meant, just using setContent 😂

2024-05-02 16:40 UTC, brandyscarney commented on core/src/components/toast/test/basic/toast.e2e.ts-snapshots/toast-translucent-color-ios-ltr-Mobile-Chrome-linux.png
Spoke with Sean about this. This screenshot wasn't broken by my PR, it was only made apparent because the pixel change was large enough to hit the minimum threshold for a diff. We don't know when the screenshots themself broke since the backdrop filter not applying wouldn't have been enough of a change to meet the minimum threshold. As a result, these screenshots are actually not beneficial to have in their current state. Firefox & Safari are also not taking proper screenshots even though browser support is there.

Translucent is working properly in all 3 browsers, so this is only broken in the screenshots. We need to investigate why it is not working in a headless Docker environment. I have created FW-6220 to investigate this more and added a comment in the test code.

2024-05-02 18:52 UTC, sean-perkins approved these changes

2024-05-02 18:52 UTC, merged