feat(avatar): add support for default (medium) size in ionic theme
ionic-team/ionic-framework pull request #29538
Opened 2024-05-22 20:47 UTC by brandyscarney

Issue number: internal

---------

## What is the current behavior?
Avatar does not have any styles on the ionic theme.

## What is the new behavior?
- Adds background, border and font styles for avatar
- Adds the sizes for the medium size and defaults the size to medium
- Adds e2e test for avatar sizes

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2024-05-22 23:57 UTC, thetaPC requested changes
Minor change

2024-05-22 23:57 UTC, thetaPC commented on core/src/components/avatar/avatar.ionic.scss
> +  border: 1px solid globals.$ionic-color-neutral-800;
```suggestion
  border: globals.$ionic-border-size-025 solid globals.$ionic-color-neutral-800;
```

2024-05-22 23:57 UTC, thetaPC commented on core/src/components/avatar/test/size/avatar.e2e.ts-snapshots/avatar-size-medium-image-ionic-md-ltr-light-Mobile-Chrome-linux.png
Just thinking out loud, not part of this PR: I wonder if we there's a way for Playwright to not had that extra space. It makes it seem that it's part of the background of avatar.

2024-05-23 13:47 UTC, brandyscarney commented on core/src/components/avatar/test/size/avatar.e2e.ts-snapshots/avatar-size-medium-image-ionic-md-ltr-light-Mobile-Chrome-linux.png
I don't see any extra space. Maybe it's the GitHub interface?

2024-05-23 15:15 UTC, BenOsodrac approved these changes

2024-05-23 15:33 UTC, OS-giulianasilva approved these changes

2024-05-23 16:12 UTC, merged