fix(typography): improve ionic global typography
ionic-team/ionic-framework pull request #29628
Opened 2024-06-17 08:54 UTC by BenOsodrac

Issue number: internal

---------

## What is the current behavior?

## What is the new behavior?

- Updated tokens utilities to no longer add font-family to utillity-classes. That is something that should only be set at a global layer, no sense to have that on a utility-class.
- Updated text token JSON as received by UX/UI Team.
- Improved tokens utilities to correctly set font-style to italic with italic font tokens.
- Adjusted typography Ionic scss to use the new typography classes and mixins based on tokens.
- Removed old basic typography test, as it was testing utility-classes that do not exist anymore.
- Added new typography test for ionic display tokens.
- Added a TODO to tackle the Inter font loading scenario, as it envolves research that impact other contexts as well.

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-06-17 11:41 UTC, OS-giulianasilva approved these changes

2024-06-17 19:51 UTC, thetaPC commented
@BenOsodrac when possible please also add the sample screen in the PR description. I recommend putting it under "Other Information." If it's added, then it would speed up the review process since we don't need to look it up manually or through the Jira ticket.

2024-06-17 19:57 UTC, thetaPC requested changes
Minor change request

2024-06-17 19:57 UTC, thetaPC commented on core/scripts/tokens/utilities.js
In the future, we should consider unifying`generateTypographyValue()` and `generateTypographyUtilityClass()` since they are the same outcome. That way we don't have to make changes to both areas everytime.

2024-06-17 19:57 UTC, thetaPC commented on packages/vue/test/base/tests/e2e/specs/inputs.cy.js
> +    cy.visit('/inputs');
Revert this since this change is not part of the tokens work.
```suggestion
    cy.visit('/inputs')
```

2024-06-17 21:01 UTC, BenOsodrac commented on core/scripts/tokens/utilities.js
Yes, I thought about that, but as they have slight differences on the outcome, the function might get a bit complex with all the exceptions

2024-06-18 00:02 UTC, thetaPC commented on core/scripts/tokens/utilities.js
Understood, then maybe we should add a comment to remind devs that if a change happens in one function then the other function needs to be updated too.

2024-06-18 00:03 UTC, thetaPC approved these changes
LGTM

2024-06-18 15:29 UTC, merged