feat(input): change fill default on ionic theme
ionic-team/ionic-framework pull request #29789
Opened 2024-08-22 13:05 UTC by BenOsodrac

Issue number: internal

---------

## What is the new behavior?

- Now the fill option default value is outline when using the Ionic theme.
- Updated snapshots.

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-08-22 14:37 UTC, joselrio approved these changes

2024-08-22 21:30 UTC, brandyscarney requested changes
I left comments on all of the screenshots showing an invalid diff.

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/bottom-content/input.e2e.ts-snapshots/input-full-bottom-outline-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/fill/input.e2e.ts-snapshots/input-fill-outline-label-stacked-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/fill/input.e2e.ts-snapshots/input-fill-outline-label-stacked-size-large-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/highlight/input.e2e.ts-snapshots/input-outline-custom-highlight-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/highlight/input.e2e.ts-snapshots/input-outline-invalid-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/shape/input.e2e.ts-snapshots/input-shape-rectangular-fill-outline-custom-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/shape/input.e2e.ts-snapshots/input-shape-rectangular-fill-outline-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/shape/input.e2e.ts-snapshots/input-shape-round-fill-outline-custom-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/shape/input.e2e.ts-snapshots/input-shape-round-fill-outline-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/shape/input.e2e.ts-snapshots/input-shape-soft-fill-outline-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/size/input.e2e.ts-snapshots/input-size-large-outline-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/size/input.e2e.ts-snapshots/input-size-large-outline-round-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/size/input.e2e.ts-snapshots/input-size-medium-outline-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/size/input.e2e.ts-snapshots/input-size-medium-outline-round-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/size/input.e2e.ts-snapshots/input-size-xlarge-outline-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/size/input.e2e.ts-snapshots/input-size-xlarge-outline-round-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/slot/input.e2e.ts-snapshots/input-slots-label-stacked-fill-outline-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/states/input.e2e.ts-snapshots/input-disabled-outline-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/states/input.e2e.ts-snapshots/input-focused-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-22 21:30 UTC, brandyscarney commented on core/src/components/input/test/states/input.e2e.ts-snapshots/input-readonly-outline-ionic-md-ltr-light-Mobile-Chrome-linux.png
Why is "Email" showing up twice here?

2024-08-23 07:23 UTC, BenOsodrac commented on core/src/components/input/input.tsx
> +    if (hasOutlineFill && theme !== 'ios') {
Ahh sorry, stupid mistake. I changed that for testing and then forgot to remove it. Then when looking at snaphots, for some reason I thought the double label was some stacking label test :)

2024-08-23 08:08 UTC, BenOsodrac commented on core/src/components/input/input.tsx
> +    if (hasOutlineFill && theme !== 'ios') {
@brandyscarney I reverted it and updated snapshots!

2024-08-23 09:59 UTC, joselrio approved these changes

2024-08-23 16:24 UTC, brandyscarney approved these changes
Looks good! 👍

2024-08-23 16:47 UTC, merged