feat(radio): display as block when justify or alignment properties are defined
ionic-team/ionic-framework pull request #29801
Opened 2024-08-26 17:04 UTC by brandyscarney

Issue number: resolves #

---------

## What is the current behavior?

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-08-27 18:27 UTC, thetaPC requested changes

2024-08-27 18:27 UTC, thetaPC commented on core/src/components/radio/test/basic/index.html
The tags aren't wrapping as expected. For example, `radio-group` and `radio` are on the same line. Let's make sure the tags are on new lines as the other test pages.

2024-08-28 14:16 UTC, brandyscarney commented on core/src/components/radio/test/basic/index.html
This was done by the linter. I don't know how to fix it in prettier.

2024-08-28 15:06 UTC, thetaPC commented on core/src/components/radio/test/basic/index.html
Got it!

2024-08-29 07:12 UTC, BenOsodrac approved these changes

2024-08-29 13:40 UTC, merged