feat(select): add `modal` as interface
ionic-team/ionic-framework pull request #29972
Opened 2024-10-28 19:51 UTC by tanner-reits

Issue number: resolves internal

---------

## What is the current behavior?

Select only offers `alert`, `action-sheet`, and `popover` as interfaces

## What is the new behavior?

Adds `modal` as an interface option for `ion-select`

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-10-30 14:12 UTC, brandyscarney requested changes
This looks good overall, I left some feedback on the JIRA ticket though.

2024-10-30 14:12 UTC, brandyscarney commented on core/src/components/select-modal/select-modal.tsx
> +      // this is a popover with checkboxes (multiple value select)
```suggestion
      // this is a modal with checkboxes (multiple value select)
```

2024-10-30 14:12 UTC, brandyscarney commented on core/src/components/select-modal/select-modal.tsx
> +    // this is a popover with radio buttons (single value select)
```suggestion
    // this is a modal with radio buttons (single value select)
```

2024-10-30 14:12 UTC, brandyscarney commented on core/src/components/select-modal/select-modal.tsx
> +    // this is a popover with checkboxes (multiple value select)
```suggestion
    // this is a modal with checkboxes (multiple value select)
```

2024-10-30 17:08 UTC, brandyscarney approved these changes
Looks good!

2024-10-31 14:01 UTC, merged

2024-11-22 00:49 UTC, Asko-Dev commented
Hi. Love the modal option ... didn't find though how to change the `Close` text on the close button without resorting to passing in entire component in options? Is it possible somehow? My app is in czech.