chore(testing): remove the default ionic bundle for the ionic theme
ionic-team/ionic-framework pull request #29974
Opened 2024-10-28 20:33 UTC by brandyscarney

Issue number: internal

---------

## What is the current behavior?
The ionic theme is still using the default bundle in the tests.

## What is the new behavior?
Removes the default bundle from the tests because it adds global component styles the ionic theme does not need. 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2024-10-28 21:32 UTC, brandyscarney commented on core/src/css/ionic/utils.bundle.ionic.scss
This file includes the CSS utilities documented here: https://ionicframework.com/docs/layout/css-utilities

2024-10-29 09:06 UTC, BenOsodrac requested changes

2024-10-29 09:06 UTC, BenOsodrac commented on core/scripts/testing/scripts.js
> +    const defaultThemeLinkTag = document.querySelector('link[href*="css/ionic.bundle.css"]');
@brandyscarney I think this file doesn't exist 🤔, or am I missing something? Maybe that's the problem, and the link on the tests pages need to be updated or removed? 

At least for Ionic Theme tests, all its needed should be the one added on line 47

2024-10-29 09:06 UTC, BenOsodrac commented on core/src/css/ionic/utils.bundle.ionic.scss
> +@import "../utils.bundle";
I'm ok with this, as mostly this brings agnostic classes. But this also brings the padding utility-classes file, that bring padding values that might not match the ones from the new Design System and we are already creating those in the _/foundations/ionic.utility_

I would instead individually import the others, like:
@import "../float-elements";
@import "../text-alignment";
@import "../text-transformation";
@import "../flex-utils";
@import "../display";

2024-10-29 09:06 UTC, BenOsodrac commented on core/src/css/ionic/utils.bundle.ionic.scss
> +@import "../utils.bundle";
```suggestion
@import "../float-elements";
@import "../text-alignment";
@import "../text-transformation";
@import "../flex-utils";
@import "../display";
```

2024-10-29 14:38 UTC, BenOsodrac approved these changes

2024-10-29 15:37 UTC, tanner-reits approved these changes
I think this is g2g

2024-10-29 19:19 UTC, brandyscarney commented on core/scripts/tokens/index.js
> +      const defaultSpaceUtilityClasses = generateDefaultSpaceUtilityClasses();
These were the only lines added - the rest is formatting

2024-10-29 19:19 UTC, brandyscarney commented on core/scripts/tokens/index.js
> +      otherUtilityClasses.push(defaultSpaceUtilityClasses);
These were the only lines added - the rest is formatting

2024-10-29 20:07 UTC, brandyscarney commented
Requesting re-review because I changed the scope of this PR.

2024-10-29 21:50 UTC, BenOsodrac approved these changes

2024-10-29 21:50 UTC, BenOsodrac commented
LGTM 🚀

2024-10-30 13:45 UTC, tanner-reits approved these changes
LGTM

2024-10-30 13:48 UTC, merged