feat(select-modal): add ionic theme styling
ionic-team/ionic-framework pull request #30007
Opened 2024-11-07 19:03 UTC by thetaPC

Issue number: internal

---------

## What is the current behavior?

`ion-select-modal` does not have styles for `ionic` theme.

## What is the new behavior?

- Added styles for `ionic` theme
- Added snapshots

No changes were made to the other interfaces. Those will continue to follow the current styles.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Preview

2024-11-07 19:35 UTC, thetaPC commented on core/src/components/item/item.ionic.scss
> -}
No longer needed and it was interfering with the focus ring.

2024-11-07 19:36 UTC, thetaPC commented on core/src/components/item/item.ionic.scss
By default, if `lines` is missing then no lines should render. The previous styles was not following this structure. This is why changes to the border were done.

2024-11-07 21:35 UTC, thetaPC commented on core/src/components/item/item.ionic.scss
> +    globals.$ion-border-size-0};
Just moved the variables to use only one `#{}`

2024-11-07 21:55 UTC, thetaPC commented on core/src/components/radio/radio.common.scss
> +}
Noticed that the select options weren't truncating with ellipsis. Moved this to common since every theme behaves the same.

2024-11-08 16:29 UTC, tanner-reits requested changes

2024-11-08 16:29 UTC, tanner-reits commented on core/src/components/select-modal/test/basic/select-modal.e2e.ts-snapshots/select-modal-diff-ionic-md-ltr-light-Mobile-Chrome-linux.png
I believe the radios should be hidden for single-select (like we do for MD theme)

2024-11-08 19:50 UTC, thetaPC commented on core/src/components/select-modal/test/basic/select-modal.e2e.ts-snapshots/select-modal-diff-ionic-md-ltr-light-Mobile-Chrome-linux.png
https://github.com/ionic-team/ionic-framework/pull/30007/commits/1df84408f701527ddb003d52544c5eccf0c9de7f

2024-11-08 21:26 UTC, tanner-reits approved these changes
LGTM!

2024-11-08 21:51 UTC, merged