feat(range): add focus styles to range
ionic-team/ionic-framework pull request #30077
Opened 2024-12-11 12:23 UTC by BenOsodrac

Issue number: internal

---------

## What is the new behavior?

- Add focus styles to ion-range when using Ionic theme.
- Add new focus test for ionic theme.
- Add new snapshots.

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-12-11 19:17 UTC, brandyscarney approved these changes

2024-12-12 18:41 UTC, thetaPC requested changes

2024-12-12 18:41 UTC, thetaPC commented on core/src/components/range/test/states/range.e2e.ts
> +      const handle = await range.locator('.range-knob-handle');
```suggestion
      const handle = range.locator('.range-knob-handle');
```

The `locator()` does not require an `await`.

2024-12-12 18:41 UTC, thetaPC commented on core/src/components/range/test/states/range.e2e.ts
> +      handle?.focus();
```suggestion
      handle.focus();
```
The optional chaining isn't needed since we know that the element exists.

2024-12-12 18:41 UTC, thetaPC commented on core/src/components/range/test/states/range.e2e.ts
> +  test.describe(title('range: focus'), () => {
```suggestion
  test.describe(title('range: states'), () => {
```
Let's give this suite a generic name in case we want to add more state tests.

2024-12-13 16:53 UTC, thetaPC approved these changes
LGTM

2024-12-13 16:54 UTC, merged